// Aquaculture.js
// Batch 1: Questions 1 - 100
// Focus: General Principles, Engineering, Water Quality, Nutrition

const aquacultureQuestions = [
    // --- AQUACULTURE ENGINEERING & PONDS ---
    { q: "Recommended slope for clay soil dike?", opts: ["1:1", "2:1", "1:2", "1:4"], a: "2:1" },
    { q: "Best soil texture for fishpond dikes?", opts: ["Sandy loam", "Clay loam", "Silt", "Pure Clay"], a: "Clay loam" },
    { q: "Standard crown width for a main dike?", opts: ["1-2 m", "2-4 m", "0.5 m", "10 m"], a: "2-4 m" },
    { q: "Type of gate used for main water control?", opts: ["Monk gate", "Sluice gate", "Pipe culvert", "Check valve"], a: "Sluice gate" },
    { q: "Best pump for high volume, low head?", opts: ["Centrifugal", "Axial flow", "Piston", "Diaphragm"], a: "Axial flow" },
    { q: "1 HP paddlewheel adds approx how much O2?", opts: ["0.1 kg/hr", "1.0-1.5 kg/hr", "5.0 kg/hr", "10 kg/hr"], a: "1.0-1.5 kg/hr" },
    { q: "Freeboard in a dike prevents?", opts: ["Seepage", "Overtopping", "Erosion", "Harvesting"], a: "Overtopping" },
    { q: "Ideal topography for brackishwater ponds?", opts: ["Flat", "Steep", "Hilly", "Mountainous"], a: "Flat" },
    { q: "Equation Q = AV calculates?", opts: ["Flow Rate", "Feed Rate", "Stocking Density", "Oxygen Demand"], a: "Flow Rate" },
    { q: "Correct orientation of rectangular ponds?", opts: ["Parallel to wind", "Perpendicular to wind", "Diagonal", "Any"], a: "Parallel to wind" },
    { q: "Berm is located between?", opts: ["Dike toe and canal", "Crown and water", "Gate and net", "Pond bottom"], a: "Dike toe and canal" },
    { q: "Prevents soil erosion on dikes?", opts: ["Planting grass", "Concrete only", "Plastic", "Removing trees"], a: "Planting grass" },
    { q: "Gate used for automatic water level control?", opts: ["Tidal gate", "Sluice gate", "Monk gate", "Standpipe"], a: "Standpipe" },
    { q: "PVC pipe class for pressurized water?", opts: ["Class 1000", "Series 1000", "Schedule 40/80", "Sanitary"], a: "Schedule 40/80" },
    { q: "Main purpose of a puddling trench?", opts: ["Anchor dike", "Prevent seepage", "Drain water", "Catch fish"], a: "Prevent seepage" },
    { q: "Mesh size 'B-net' is used for?", opts: ["Fry", "Fingerlings", "Broodstock", "Harvest"], a: "Fingerlings" },
    { q: "Function of a settling basin?", opts: ["Remove solids", "Add oxygen", "Heat water", "Mix feed"], a: "Remove solids" },
    { q: "Ratio of slope for sandy soil?", opts: ["1:1", "3:1 or 4:1", "1:2", "Vertical"], a: "3:1 or 4:1" },
    { q: "Concrete curing time before use?", opts: ["1 day", "7 days", "28 days", "3 months"], a: "28 days" },
    { q: "Difference between Pen and Cage?", opts: ["Pen has no floor", "Cage has no floor", "Pen floats", "Cage is fixed"], a: "Pen has no floor" },

    // --- WATER QUALITY ---
    { q: "Primary toxic metabolite in RAS?", opts: ["Nitrate", "Ammonia", "Nitrite", "CO2"], a: "Ammonia" },
    { q: "Main purpose of liming?", opts: ["Disinfect", "Increase Alkalinity/pH", "Kill predators", "Fertilize"], a: "Increase Alkalinity/pH" },
    { q: "Standard time to check DO?", opts: ["12:00 MN", "6:00 AM", "12:00 NN", "3:00 PM"], a: "6:00 AM" },
    { q: "Specific gravity of seawater?", opts: ["1.000", "1.025", "1.500", "0.900"], a: "1.025" },
    { q: "Chemical to remove chlorine?", opts: ["Na Thiosulfate", "Formalin", "Copper Sulfate", "Lime"], a: "Na Thiosulfate" },
    { q: "Optimal pH range for fish?", opts: ["4.0-5.0", "6.5-8.5", "9.0-10.0", "2.0-3.0"], a: "6.5-8.5" },
    { q: "Hardness measures?", opts: ["Ca and Mg", "Na and K", "Fe and Al", "H ions"], a: "Ca and Mg" },
    { q: "Device to measure turbidity?", opts: ["Refractometer", "Secchi Disk", "Thermometer", "pH Meter"], a: "Secchi Disk" },
    { q: "Lethal DO level is below?", opts: ["5 ppm", "2-3 ppm", "10 ppm", "20 ppm"], a: "2-3 ppm" },
    { q: "Toxic form of Ammonia?", opts: ["NH3 (Unionized)", "NH4+ (Ionized)", "NO2", "NO3"], a: "NH3 (Unionized)" },
    { q: "Cause of muddy taste in Tilapia?", opts: ["Geosmin", "Ammonia", "Nitrite", "Chlorine"], a: "Geosmin" },
    { q: "Tea seed cake kills?", opts: ["Snails/Fish", "Bacteria", "Viruses", "Algae"], a: "Snails/Fish" },
    { q: "Fertilizer 46-0-0 is?", opts: ["Urea", "Amm. Phos", "Potash", "Complete"], a: "Urea" },
    { q: "Ratio of N:P for diatoms?", opts: ["1:1", "10:1 - 20:1", "100:1", "500:1"], a: "10:1 - 20:1" },
    { q: "Gas causing Brown Blood Disease?", opts: ["Nitrite", "Ammonia", "Nitrate", "CO2"], a: "Nitrite" },
    { q: "Salinity unit of measurement?", opts: ["ppm", "ppt", "mg/L", "psi"], a: "ppt" },
    { q: "Instrument for salinity?", opts: ["Refractometer", "Barometer", "Hygrometer", "Anemometer"], a: "Refractometer" },
    { q: "Effect of high CO2 on fish?", opts: ["Acidosis", "Alkalosis", "Necrosis", "Gigantism"], a: "Acidosis" },
    { q: "Source of dissolved oxygen in day?", opts: ["Photosynthesis", "Respiration", "Decomposition", "Feeding"], a: "Photosynthesis" },
    { q: "Stratification of water temperature?", opts: ["Thermocline", "Halocline", "Pycnocline", "Chemocline"], a: "Thermocline" },

    // --- NUTRITION & FEEDING ---
    { q: "Calculate FCR: 1500kg feed / 1200kg fish.", opts: ["0.8", "1.25", "1.5", "1.2"], a: "1.25" },
    { q: "Limiting amino acid in plants?", opts: ["Lysine", "Glutamine", "Alanine", "Proline"], a: "Lysine" },
    { q: "Recommended CP for Tilapia fry?", opts: ["20%", "30%", "40-45%", "60%"], a: "40-45%" },
    { q: "Vitamin C deficiency causes?", opts: ["Broken back", "Blindness", "Fin rot", "Dropsy"], a: "Broken back" },
    { q: "Floating feed production method?", opts: ["Extrusion", "Pelleting", "Mashing", "Crumbling"], a: "Extrusion" },
    { q: "Additive for red color?", opts: ["Astaxanthin", "Vitamin C", "Binder", "Antibiotic"], a: "Astaxanthin" },
    { q: "Most expensive feed component?", opts: ["Carbohydrates", "Protein", "Lipids", "Vitamins"], a: "Protein" },
    { q: "Formula for Daily Feeding Rate?", opts: ["ABW x Stock x Rate", "Feed / Harvest", "Harvest / Area", "Feed / Days"], a: "ABW x Stock x Rate" },
    { q: "Lipid source rich in HUFA?", opts: ["Fish oil", "Coconut oil", "Corn oil", "Soybean oil"], a: "Fish oil" },
    { q: "Binder for farm-made feeds?", opts: ["Cassava starch", "Sand", "Limestone", "Salt"], a: "Cassava starch" },
    { q: "Anti-nutritional factor in soybean?", opts: ["Trypsin inhibitor", "Gossypol", "Mimosine", "Thiaminase"], a: "Trypsin inhibitor" },
    { q: "Ipil-ipil toxin?", opts: ["Mimosine", "Gossypol", "Cyanide", "Phytate"], a: "Mimosine" },
    { q: "Feeding method: 'Ad libitum'?", opts: ["To satiety", "Fixed ration", "Percent body weight", "Hourly"], a: "To satiety" },
    { q: "Gross energy of Fat (kcal/g)?", opts: ["4.1", "5.6", "9.5", "2.5"], a: "9.5" },
    { q: "Sinking pellets are made by?", opts: ["Steam pelleting", "Extrusion", "Baking", "Boiling"], a: "Steam pelleting" },
    { q: "Proximate analysis measures?", opts: ["Crude Protein", "Amino Acids", "Vitamins", "Digestibility"], a: "Crude Protein" },
    { q: "Kjeldahl method measures?", opts: ["Nitrogen/Protein", "Fat", "Fiber", "Ash"], a: "Nitrogen/Protein" },
    { q: "Soxhlet method measures?", opts: ["Crude Fat", "Protein", "Fiber", "Moisture"], a: "Crude Fat" },
    { q: "Ash content represents?", opts: ["Minerals", "Vitamins", "Carbs", "Water"], a: "Minerals" },
    { q: "Feed storage humidity max?", opts: ["10%", "13%", "20%", "50%"], a: "13%" },

    // --- HATCHERY & BIOLOGY ---
    { q: "Scientific name: Milkfish?", opts: ["Chanos chanos", "O. niloticus", "L. calcarifer", "M. cephalus"], a: "Chanos chanos" },
    { q: "Scientific name: Black Tiger Shrimp?", opts: ["P. monodon", "P. vannamei", "S. serrata", "Macrobrachium"], a: "P. monodon" },
    { q: "Scientific name: Mud Crab?", opts: ["Scylla serrata", "Portunus pelagicus", "P. monodon", "Chanos chanos"], a: "Scylla serrata" },
    { q: "Scientific name: Sea Bass?", opts: ["Lates calcarifer", "E. coioides", "L. argentimaculatus", "Rachycentron"], a: "Lates calcarifer" },
    { q: "Hormone for Tilapia sex reversal?", opts: ["17-a Methyltestosterone", "Estradiol", "LHRHa", "HCG"], a: "17-a Methyltestosterone" },
    { q: "Hormone for induced spawning?", opts: ["LHRHa", "Testosterone", "Progesterone", "Thyroxine"], a: "LHRHa" },
    { q: "Rotifers are feed for?", opts: ["Grouper larvae", "Adult Tilapia", "Shrimp", "Crab"], a: "Grouper larvae" },
    { q: "Artemia common name?", opts: ["Brine shrimp", "Water flea", "Copepod", "Rotifer"], a: "Brine shrimp" },
    { q: "Green Water Tech organism?", opts: ["Chlorella", "Sargassum", "Duckweed", "Lab-lab"], a: "Chlorella" },
    { q: "First feeding stage of shrimp?", opts: ["Zoea", "Nauplius", "Mysis", "Post-larva"], a: "Zoea" },
    { q: "Nauplius feeds on?", opts: ["Yolk sac", "Algae", "Artemia", "Pellets"], a: "Yolk sac" },
    { q: "Female crab with eggs?", opts: ["Berried", "Pregnant", "Gravid", "Spawning"], a: "Berried" },
    { q: "Eyestalk ablation induces?", opts: ["Maturation", "Growth", "Molting", "Death"], a: "Maturation" },
    { q: "Sabalo refers to?", opts: ["Milkfish Breeder", "Fry", "Fingerling", "Market size"], a: "Milkfish Breeder" },
    { q: "Stocking density extensive Tilapia?", opts: ["1-2 pcs/m2", "5-10 pcs/m2", "50 pcs/m2", "100 pcs/m2"], a: "1-2 pcs/m2" },
    { q: "Bangus fry gathering gear?", opts: ["Sweeper", "Trawl", "Purse seine", "Gill net"], a: "Sweeper" },
    { q: "Tilapia incubation period?", opts: ["3-5 days", "10-15 days", "24 hours", "1 month"], a: "3-5 days" },
    { q: "Carp pituitary gland uses?", opts: ["Induced spawning", "Sex reversal", "Growth", "Color"], a: "Induced spawning" },
    { q: "Hapa net function?", opts: ["Nursing/Breeding", "Filtering water", "Catching wild fish", "Drying feed"], a: "Nursing/Breeding" },
    { q: "Scientific name: Giant FW Prawn?", opts: ["M. rosenbergii", "P. monodon", "L. vannamei", "S. serrata"], a: "M. rosenbergii" },

    // --- DISEASES & HEALTH ---
    { q: "Cause of White Spot (WSSV)?", opts: ["Virus", "Bacteria", "Fungus", "Parasite"], a: "Virus" },
    { q: "Luminous Vibriosis cause?", opts: ["Vibrio harveyi", "V. cholerae", "E. coli", "Salmonella"], a: "Vibrio harveyi" },
    { q: "Ichthyophthirius multifiliis?", opts: ["White Spot (Ich)", "Fin Rot", "Dropsy", "VNN"], a: "White Spot (Ich)" },
    { q: "Argulus common name?", opts: ["Fish louse", "Anchor worm", "Gill fluke", "Skin fluke"], a: "Fish louse" },
    { q: "Probiotics are?", opts: ["Beneficial bacteria", "Antibiotics", "Vitamins", "Vaccines"], a: "Beneficial bacteria" },
    { q: "VNN symptom in Grouper?", opts: ["Spinning/Whirling", "Red spots", "Pop-eye", "White feces"], a: "Spinning/Whirling" },
    { q: "Fungal treatment?", opts: ["Salt / Methylene Blue", "Antibiotics", "Probiotics", "Lime"], a: "Salt / Methylene Blue" },
    { q: "Vibrio is?", opts: ["Gram-negative", "Gram-positive", "Viral", "Fungal"], a: "Gram-negative" },
    { q: "PCR stands for?", opts: ["Polymerase Chain Reaction", "Post Culture Review", "Pond Clean", "Prot-Carb Ratio"], a: "Polymerase Chain Reaction" },
    { q: "Streptococcus attacks?", opts: ["Brain/Eyes (Pop-eye)", "Gills", "Fins", "Stomach"], a: "Brain/Eyes (Pop-eye)" },
    { q: "Formalin is used for?", opts: ["Ectoparasites", "Viral infection", "Nutrition", "pH control"], a: "Ectoparasites" },
    { q: "Lernea common name?", opts: ["Anchor worm", "Fish louse", "Fluke", "Leech"], a: "Anchor worm" },
    { q: "Tilapia Lake Virus affects?", opts: ["Eyes/Liver", "Gills only", "Skin only", "Fins only"], a: "Eyes/Liver" },
    { q: "EMS in shrimp stands for?", opts: ["Early Mortality Syndrome", "Energy Mass System", "Eat More Shrimp", "Egg Maturation Stage"], a: "Early Mortality Syndrome" },
    { q: "EMS is also called?", opts: ["AHPND", "WSSV", "MBV", "IHHNV"], a: "AHPND" },
    { q: "Prevention of disease best method?", opts: ["Biosecurity", "Antibiotics", "Overstocking", "Water exchange"], a: "Biosecurity" },
    { q: "Vector for WSSV?", opts: ["Crabs/Carriers", "Birds", "Wind", "Sun"], a: "Crabs/Carriers" },
    { q: "Trichodina is a?", opts: ["Protozoan", "Virus", "Bacterium", "Worm"], a: "Protozoan" },
    { q: "Treatment for bacterial infection?", opts: ["Antibiotics", "Vitamins", "Lime", "Fertilizer"], a: "Antibiotics" },
    { q: "Vaccines stimulate?", opts: ["Antibody production", "Growth", "Appetite", "Digestion"], a: "Antibody production" },
  // --- BATCH 2: QUESTIONS 101-200 ---
    // --- INTEGRATED FARMING & SPECIALIZED SYSTEMS ---
    { q: "Rice-fish culture trench width?", opts: ["1 meter", "5 meters", "10 cm", "0.5 meters"], a: "1 meter" },
    { q: "Rice variety best for Rice-Fish culture?", opts: ["HYV / Resistant to lodging", "Tall variety", "Sticky rice", "Upland rice"], a: "HYV / Resistant to lodging" },
    { q: "Aquaponics: Bacteria converting Nitrite to Nitrate?", opts: ["Nitrobacter", "Nitrosomonas", "Bacillus", "Vibrio"], a: "Nitrobacter" },
    { q: "Ratio of Fish Tank to Grow Bed (Volume)?", opts: ["1:1 to 1:2", "1:10", "10:1", "50:1"], a: "1:1 to 1:2" },
    { q: "Hydroponic media often used?", opts: ["Clay pebbles (LECA)", "Soil", "Mud", "Sand"], a: "Clay pebbles (LECA)" },
    { q: "RAS component removing fine solids?", opts: ["Drum Filter", "Biofilter", "UV Sterilizer", "Oxygen cone"], a: "Drum Filter" },
    { q: "RAS component removing dissolved Ammonia?", opts: ["Biofilter", "Drum Filter", "Protein Skimmer", "Sump"], a: "Biofilter" },
    { q: "RAS component for CO2 removal?", opts: ["Degasser / Stripping column", "UV Light", "Sand Filter", "Heater"], a: "Degasser / Stripping column" },
    { q: "Protein skimmer works by?", opts: ["Foam fractionation", "Sedimentation", "Biological action", "Chemical reaction"], a: "Foam fractionation" },
    { q: "UV sterilization effectiveness depends on?", opts: ["Water clarity/transmittance", "Water temperature", "Salinity", "pH"], a: "Water clarity/transmittance" },

    // --- MARICULTURE (Mussels, Oysters, Seaweeds) ---
    { q: "Bamboo pole method for mussels is called?", opts: ["Stake method", "Raft method", "Tray method", "Broadcast"], a: "Stake method" },
    { q: "Distance between monoslines in seaweed farm?", opts: ["1 meter", "10 meters", "50 cm", "5 meters"], a: "1 meter" },
    { q: "Depth of planting for Eucheuma?", opts: ["0.5m below surface", "Bottom", "Surface", "5m deep"], a: "0.5m below surface" },
    { q: "Best bottom type for seaweed farming?", opts: ["Sandy-rocky / Coral rubble", "Pure mud", "Silt", "Sludge"], a: "Sandy-rocky / Coral rubble" },
    { q: "Spatfall refers to?", opts: ["Settlement of mollusk larvae", "Fish spawning", "Algal bloom", "Disease outbreak"], a: "Settlement of mollusk larvae" },
    { q: "Ideal salinity for Oyster farming?", opts: ["15-25 ppt", "35 ppt", "0 ppt", "40+ ppt"], a: "15-25 ppt" },
    { q: "Mussel scientific name (Green)?", opts: ["Perna viridis", "Crassostrea iredalei", "Pinctada maxima", "Haliotis asinina"], a: "Perna viridis" },
    { q: "Oyster scientific name (Slipper)?", opts: ["Crassostrea iredalei", "Perna viridis", "Anadara granosa", "Placuna placenta"], a: "Crassostrea iredalei" },
    { q: "Window pane shell scientific name?", opts: ["Placuna placenta", "Tridacna gigas", "Pinctada margaritifera", "Turbo marmoratus"], a: "Placuna placenta" },
    { q: "Pearl farm operating depth?", opts: ["20-30 meters", "1 meter", "5 meters", "100 meters"], a: "20-30 meters" },

    // --- HATCHERY TECHNIQUES (Part 2) ---
    { q: "Dry method of fertilization?", opts: ["Mix eggs and sperm dry", "Add water first", "Mix in tank", "Use chemicals"], a: "Mix eggs and sperm dry" },
    { q: "Removing stickiness of carp eggs?", opts: ["Fuller's earth / Urea-salt", "Oil", "Acid", "Sugar"], a: "Fuller's earth / Urea-salt" },
    { q: "Optimum temperature for Tilapia hatching?", opts: ["28-30°C", "20-22°C", "35-37°C", "15°C"], a: "28-30°C" },
    { q: "Counting fry by volume?", opts: ["Volumetric method", "Gravimetric method", "Visual estimation", "Individual counting"], a: "Volumetric method" },
    { q: "Anaesthetics for fish transport?", opts: ["MS-222 / Clove Oil", "Formalin", "Chlorine", "Antibiotic"], a: "MS-222 / Clove Oil" },
    { q: "Standard packing density Milkfish fry (plastic)?", opts: ["5,000 - 10,000 / bag", "100 / bag", "1,000,000 / bag", "50 / bag"], a: "5,000 - 10,000 / bag" },
    { q: "Feed for 'mysis' stage shrimp?", opts: ["Artemia / Algae", "Fish meat", "Pellets", "Egg yolk"], a: "Artemia / Algae" },
    { q: "Which is a 'Non-Penaeid' shrimp?", opts: ["Macrobrachium", "Penaeus monodon", "Penaeus vannamei", "Metapenaeus"], a: "Macrobrachium" },
    { q: "Macrobrachium larvae require?", opts: ["Brackishwater (Green water)", "Freshwater", "Pure seawater", "Distilled water"], a: "Brackishwater (Green water)" },
    { q: "Survival rate formula?", opts: ["(Harvest / Stock) x 100", "(Stock / Harvest) x 100", "Harvest - Stock", "Stock + Harvest"], a: "(Harvest / Stock) x 100" },

    // --- NUTRITION CALCULATIONS & BIOCHEMISTRY ---
    { q: "Pearson Square is used for?", opts: ["Feed Formulation", "Water volume", "Area calculation", "Diagnosis"], a: "Feed Formulation" },
    { q: "Calculate Protein: 60% Fishmeal, 20% Rice Bran (Given FM=60% CP, RB=12% CP)?", opts: ["38.4%", "41%", "36%", "50%"], a: "38.4%" },
    { q: "Energy value of Carbohydrates?", opts: ["4.1 kcal/g", "9.5 kcal/g", "5.6 kcal/g", "2.0 kcal/g"], a: "4.1 kcal/g" },
    { q: "Energy value of Protein?", opts: ["5.6 kcal/g (Gross)", "9.5 kcal/g", "2.0 kcal/g", "10 kcal/g"], a: "5.6 kcal/g (Gross)" },
    { q: "Essential Fatty Acid for marine fish?", opts: ["DHA and EPA", "Linoleic Acid", "Oleic Acid", "Stearic Acid"], a: "DHA and EPA" },
    { q: "Protein sparing effect is achieved by?", opts: ["Lipids/Carbohydrates", "Vitamins", "Minerals", "Water"], a: "Lipids/Carbohydrates" },
    { q: "Deficiency of Zinc causes?", opts: ["Dwarfism / Cataracts", "Scoliosis", "Anemia", "Hemorrhage"], a: "Dwarfism / Cataracts" },
    { q: "Yellow corn provides?", opts: ["Carbohydrates + Carotene", "Protein", "Fat", "Fiber"], a: "Carbohydrates + Carotene" },
    { q: "Rice bran is high in?", opts: ["Vitamin B / Fiber", "Protein", "Vitamin C", "Calcium"], a: "Vitamin B / Fiber" },
    { q: "Copra meal limitation?", opts: ["High fiber / Aflatoxin risk", "High protein", "Too expensive", "Toxic"], a: "High fiber / Aflatoxin risk" },
    { q: "Fish meal replacement often used?", opts: ["Soybean meal", "Cornstarch", "Rice hull", "Sawdust"], a: "Soybean meal" },
    { q: "Amino acid Methionine is rich in?", opts: ["Fish meal", "Plant meal", "Corn", "Cassava"], a: "Fish meal" },
    { q: "Feed storage pest?", opts: ["Weevils / Rodents", "Birds", "Cats", "Dogs"], a: "Weevils / Rodents" },
    { q: "Rancidity affects which nutrient?", opts: ["Fats / Lipids", "Proteins", "Carbohydrates", "Minerals"], a: "Fats / Lipids" },
    { q: "Antioxidant added to feed?", opts: ["BHT / Ethoxyquin", "Salt", "Sugar", "Lime"], a: "BHT / Ethoxyquin" },

    // --- AQUACULTURE ENGINEERING (Part 2) ---
    { q: "Manning's Roughness Coefficient (n) for Earth canals?", opts: ["0.020 - 0.025", "0.010 - 0.013", "0.050", "0.100"], a: "0.020 - 0.025" },
    { q: "Trapezoidal canal area formula?", opts: ["A = d (b + zd)", "A = L x W", "A = πr2", "A = 0.5 bh"], a: "A = d (b + zd)" },
    { q: "Standard side slope (z) for sandy loam?", opts: ["2:1", "1:1", "0:1", "0.5:1"], a: "2:1" },
    { q: "Velocity of water preventing erosion?", opts: ["Permissible velocity", "Critical velocity", "Terminal velocity", "Maximum velocity"], a: "Permissible velocity" },
    { q: "Velocity of water preventing siltation?", opts: ["Non-silting velocity", "High velocity", "Low velocity", "Zero velocity"], a: "Non-silting velocity" },
    { q: "Device measuring atmospheric pressure?", opts: ["Barometer", "Thermometer", "Anemometer", "Psychrometer"], a: "Barometer" },
    { q: "Hp required to lift 550 lb, 1 ft, in 1 sec?", opts: ["1 Hp", "5 Hp", "10 Hp", "0.5 Hp"], a: "1 Hp" },
    { q: "1 Horsepower (Electrical) equals?", opts: ["746 Watts", "1000 Watts", "500 Watts", "220 Watts"], a: "746 Watts" },
    { q: "Voltage standard in Philippines?", opts: ["220V / 60Hz", "110V / 60Hz", "240V / 50Hz", "100V / 50Hz"], a: "220V / 60Hz" },
    { q: "Pipe color for potable water?", opts: ["Blue", "Orange", "Red", "Green"], a: "Blue" },
    { q: "Pipe color for electrical conduit?", opts: ["Orange", "Blue", "Red", "Black"], a: "Orange" },
    { q: "Net mesh size #17 means?", opts: ["17 knots per foot (obsolete) or mm", "17 inches", "17 cm", "17 meters"], a: "17 knots per foot (obsolete) or mm" }, // *Note: In PH context, # often refers to kgs or specific legacy numbering*
    { q: "Calculating Biomass?", opts: ["ABW x Survival Rate x Stock", "Feed / 2", "Area x Depth", "Weight + Length"], a: "ABW x Survival Rate x Stock" },
    { q: "Meaning of FCR?", opts: ["Feed Conversion Ratio", "Fish Catch Rate", "Farm Care Rule", "Feed Cost Return"], a: "Feed Conversion Ratio" },
    { q: "Lower FCR means?", opts: ["Better efficiency", "Worse efficiency", "More feed used", "Slower growth"], a: "Better efficiency" },

    // --- WATER QUALITY & CHEMISTRY (Part 2) ---
    { q: "Buffer system of water?", opts: ["Carbonate-Bicarbonate", "Nitrate-Nitrite", "Oxygen-Ozone", "Iron-Manganese"], a: "Carbonate-Bicarbonate" },
    { q: "Alkalinity is the capacity to?", opts: ["Neutralize acid", "Neutralize base", "Dissolve oxygen", "Precipitate solids"], a: "Neutralize acid" },
    { q: "Best time to apply lime?", opts: ["Pond preparation", "During harvest", "Before rain", "Midnight"], a: "Pond preparation" },
    { q: "Burnt lime formula?", opts: ["CaO", "CaCO3", "Ca(OH)2", "CaMg(CO3)2"], a: "CaO" },
    { q: "Agricultural lime formula?", opts: ["CaCO3", "CaO", "Ca(OH)2", "CaSO4"], a: "CaCO3" },
    { q: "Hydrated lime formula?", opts: ["Ca(OH)2", "CaO", "CaCO3", "MgCO3"], a: "Ca(OH)2" },
    { q: "Gypsum (CaSO4) is used to?", opts: ["Correct coagulation / turbidity", "Increase pH", "Kill bacteria", "Fertilize"], a: "Correct coagulation / turbidity" },
    { q: "Teaseed cake active ingredient?", opts: ["Saponin", "Rotenone", "Nicotine", "Chlorine"], a: "Saponin" },
    { q: "Rotenone (Derris root) degrades in?", opts: ["Sunlight / 2-3 days", "Never", "1 hour", "1 year"], a: "Sunlight / 2-3 days" },
    { q: "Tobacco dust active ingredient?", opts: ["Nicotine", "Saponin", "Cyanide", "Tannin"], a: "Nicotine" },
    { q: "Unit of turbidity?", opts: ["NTU", "ppm", "mg/L", "psi"], a: "NTU" },
    { q: "Biological Oxygen Demand (BOD) measures?", opts: ["O2 used by bacteria/organic matter", "O2 used by fish", "Total O2", "O2 from algae"], a: "O2 used by bacteria/organic matter" },
    { q: "Redox potential measures?", opts: ["Oxidation-Reduction status", "pH", "Temperature", "Salinity"], a: "Oxidation-Reduction status" },
    { q: "Negative Redox potential indicates?", opts: ["Anaerobic/Reducing conditions", "Aerobic", "Clean water", "High oxygen"], a: "Anaerobic/Reducing conditions" },
    { q: "H2S (Hydrogen Sulfide) smells like?", opts: ["Rotten eggs", "Bleach", "Earth", "Fish"], a: "Rotten eggs" },
    { q: "H2S is toxic at?", opts: ["0.01 ppm", "10 ppm", "100 ppm", "1 ppm"], a: "0.01 ppm" },
    { q: "Source of H2S?", opts: ["Anaerobic decomposition", "Photosynthesis", "Aeration", "Rain"], a: "Anaerobic decomposition" },
    { q: "Control for H2S?", opts: ["Aeration / Probiotics / KMnO4", "Adding feed", "Covering pond", "Adding salt"], a: "Aeration / Probiotics / KMnO4" },
    { q: "Relationship of pH and Ammonia toxicity?", opts: ["High pH = High toxicity", "Low pH = High toxicity", "No relation", "Neutral pH = Toxic"], a: "High pH = High toxicity" },
    { q: "Relationship of Temp and Ammonia toxicity?", opts: ["High Temp = High toxicity", "Low Temp = High toxicity", "No relation", "Constant"], a: "High Temp = High toxicity" },

    // --- MISC AQUACULTURE ---
    { q: "Golden Apple Snail is a pest in?", opts: ["Rice-Fish / Ponds", "Deep sea", "Cages", "Hatchery"], a: "Rice-Fish / Ponds" },
    { q: "Scientific name of Golden Kuhol?", opts: ["Pomacea canaliculata", "Pila conica", "Vivipara angularis", "Achatina fulica"], a: "Pomacea canaliculata" },
    { q: "Invasive species example?", opts: ["Janitor Fish (Pterygoplichthys)", "Milkfish", "Tilapia (cultured)", "Carp"], a: "Janitor Fish (Pterygoplichthys)" },
    { q: "Knifefish pest scientific name?", opts: ["Chitala ornata", "Chanos chanos", "Clarias batrachus", "Anabas testudineus"], a: "Chitala ornata" },
    { q: "Tilapia introduction to PH year?", opts: ["1950 (Mozambque)", "1900", "2000", "1800"], a: "1950 (Mozambque)" },
    { q: "Nile Tilapia introduced in PH?", opts: ["1970s", "1950s", "1990s", "1920s"], a: "1970s" },
    { q: "Father of Tilapia sex reversal in PH?", opts: ["Dr. Rafael Guerrero III", "Dr. Angel Alcala", "Dr. Gavino Trono", "Dr. Jurgenne Primavera"], a: "Dr. Rafael Guerrero III" },
    { q: "National Scientist for Seaweeds?", opts: ["Dr. Gavino Trono", "Dr. Rafael Guerrero", "Dr. Edgardo Gomez", "Dr. Angel Alcala"], a: "Dr. Gavino Trono" },
    { q: "Feed storage: First In First Out?", opts: ["FIFO", "LIFO", "FILO", "JIT"], a: "FIFO" },
    { q: "Using lights to attract plankton for fry?", opts: ["Phototaxis", "Chemotaxis", "Rheotaxis", "Thigmotaxis"], a: "Phototaxis" },
  // --- BATCH 3: QUESTIONS 201-300 ---
    // --- GENETICS & BREEDING PRINCIPLES ---
    { q: "Basic unit of inheritance?", opts: ["Gene", "Chromosome", "DNA", "RNA"], a: "Gene" },
    { q: "Organism with 2 sets of chromosomes?", opts: ["Diploid (2n)", "Haploid (n)", "Triploid (3n)", "Tetraploid (4n)"], a: "Diploid (2n)" },
    { q: "Gametes (sperm/egg) are?", opts: ["Haploid (n)", "Diploid (2n)", "Triploid (3n)", "Polyploid"], a: "Haploid (n)" },
    { q: "Process of cell division for gametes?", opts: ["Meiosis", "Mitosis", "Binary fission", "Budding"], a: "Meiosis" },
    { q: "Process of cell division for growth?", opts: ["Mitosis", "Meiosis", "Fusion", "Recombination"], a: "Mitosis" },
    { q: "Condition where an organism has 3 sets of chromosomes?", opts: ["Triploidy", "Diploidy", "Aneuploidy", "Monoploidy"], a: "Triploidy" },
    { q: "Triploid fish are generally?", opts: ["Sterile / Faster growing", "Fertile", "Smaller", "Disease prone"], a: "Sterile / Faster growing" },
    { q: "Method to induce triploidy?", opts: ["Thermal/Pressure Shock", "Chemical feeding", "Radiation", "Salinity shock"], a: "Thermal/Pressure Shock" },
    { q: "Phenotype refers to?", opts: ["Physical appearance", "Genetic makeup", "Family tree", "Mutation rate"], a: "Physical appearance" },
    { q: "Genotype refers to?", opts: ["Genetic makeup", "Physical size", "Color", "Weight"], a: "Genetic makeup" },
    { q: "Mating of closely related individuals?", opts: ["Inbreeding", "Crossbreeding", "Hybridization", "Outcrossing"], a: "Inbreeding" },
    { q: "Result of inbreeding?", opts: ["Inbreeding Depression (Deformities)", "Hybrid Vigor", "Faster Growth", "Better Survival"], a: "Inbreeding Depression (Deformities)" },
    { q: "Mating of different species?", opts: ["Hybridization", "Inbreeding", "Cloning", "Selfing"], a: "Hybridization" },
    { q: "Superiority of hybrid over parents?", opts: ["Heterosis / Hybrid Vigor", "Depression", "Recessiveness", "Dominance"], a: "Heterosis / Hybrid Vigor" },
    { q: "GIFT Tilapia stands for?", opts: ["Genetically Improved Farmed Tilapia", "Growth Improvement For Tilapia", "Global Institute For Tilapia", "Genetic International Fish Trade"], a: "Genetically Improved Farmed Tilapia" },
    { q: "YY Male technology produces?", opts: ["All-male progeny (GMT)", "All-female progeny", "Sterile fish", "Hermaphrodites"], a: "All-male progeny (GMT)" },
    { q: "Cryopreservation is used for?", opts: ["Sperm banking", "Cooking", "Transporting live fish", "Killing parasites"], a: "Sperm banking" },
    { q: "Chemical used in cryopreservation?", opts: ["Liquid Nitrogen (-196C)", "Dry Ice", "Formalin", "Alcohol"], a: "Liquid Nitrogen (-196C)" },
    { q: "Protectant added to sperm before freezing?", opts: ["Cryoprotectant (DMSO/Methanol)", "Antibiotic", "Water", "Salt"], a: "Cryoprotectant (DMSO/Methanol)" },
    { q: "Selection based on individual performance?", opts: ["Mass Selection", "Family Selection", "Marker Assisted", "Natural Selection"], a: "Mass Selection" },

    // --- CARP & CATFISH CULTURE ---
    { q: "Scientific name of Common Carp?", opts: ["Cyprinus carpio", "Aristichthys nobilis", "Hypophthalmichthys molitrix", "Ctenopharyngodon idella"], a: "Cyprinus carpio" },
    { q: "Scientific name of Bighead Carp?", opts: ["Aristichthys nobilis", "Cyprinus carpio", "Chanos chanos", "Clarias batrachus"], a: "Aristichthys nobilis" },
    { q: "Scientific name of Grass Carp?", opts: ["Ctenopharyngodon idella", "Cyprinus carpio", "Mylopharyngodon piceus", "Labeo rohita"], a: "Ctenopharyngodon idella" },
    { q: "Scientific name of Silver Carp?", opts: ["Hypophthalmichthys molitrix", "Cyprinus carpio", "Clarias gariepinus", "Pangasius hypophthalmus"], a: "Hypophthalmichthys molitrix" },
    { q: "Scientific name of African Catfish?", opts: ["Clarias gariepinus", "Clarias batrachus", "Pangasius", "Ictalurus"], a: "Clarias gariepinus" },
    { q: "Native catfish (Hito) scientific name?", opts: ["Clarias batrachus", "Clarias macrocephalus", "Clarias gariepinus", "Arius manillensis"], a: "Clarias macrocephalus" },
    { q: "Pangasius catfish scientific name?", opts: ["Pangasius hypophthalmus", "Clarias gariepinus", "Ictalurus punctatus", "Silurus glanis"], a: "Pangasius hypophthalmus" },
    { q: "Carp organ used for grinding food?", opts: ["Pharyngeal teeth", "Stomach", "Gizzard", "Beak"], a: "Pharyngeal teeth" },
    { q: "Grass carp feeds primarily on?", opts: ["Macrophytes / Plants", "Zooplankton", "Small fish", "Detritus"], a: "Macrophytes / Plants" },
    { q: "Bighead carp feeds primarily on?", opts: ["Zooplankton", "Phytoplankton", "Snails", "Plants"], a: "Zooplankton" },
    { q: "Silver carp feeds primarily on?", opts: ["Phytoplankton", "Zooplankton", "Insects", "Worms"], a: "Phytoplankton" },
    { q: "Spawning habit of Chinese Carps?", opts: ["Riverine (Running water)", "Stagnant water", "Marine", "Estuary"], a: "Riverine (Running water)" },
    { q: "Adhesiveness of Common Carp eggs?", opts: ["Adhesive", "Non-adhesive", "Floating", "Pelagic"], a: "Adhesive" },
    { q: "Material to collect carp eggs?", opts: ["Kakaban", "Net", "Bucket", "Sand"], a: "Kakaban" },
    { q: "Catfish are tolerant to low DO because?", opts: ["Arborescent organ", "Labyrinth organ", "Gills", "Swim bladder"], a: "Arborescent organ" },
    { q: "Feeding habit of Clarias catfish?", opts: ["Omnivorous / Carnivorous", "Herbivorous", "Planktivorous", "Detritivorous"], a: "Omnivorous / Carnivorous" },
    { q: "Cannibalism is common in?", opts: ["Catfish larvae", "Carp larvae", "Milkfish fry", "Tilapia fry"], a: "Catfish larvae" },
    { q: "Term for removing eggs from female manually?", opts: ["Stripping", "Milking", "Spawning", "Extracting"], a: "Stripping" },
    { q: "Fluid containing sperm?", opts: ["Milt", "Roe", "Plasma", "Serum"], a: "Milt" },
    { q: "Ideal ratio of Male:Female for Carp breeding?", opts: ["1:1 or 2:1", "1:10", "10:1", "5:1"], a: "1:1 or 2:1" },

    // --- ABALONE & OTHER INVERTEBRATES ---
    { q: "Scientific name of Donkey's Ear Abalone?", opts: ["Haliotis asinina", "Haliotis discus", "Haliotis rufescens", "Perna viridis"], a: "Haliotis asinina" },
    { q: "Larval stage of Abalone (free swimming)?", opts: ["Trochophore / Veliger", "Nauplius", "Zoea", "Mysis"], a: "Trochophore / Veliger" },
    { q: "Settlement cue for Abalone larvae?", opts: ["Diatom film / Coralline algae", "Clean glass", "Sand", "Mud"], a: "Diatom film / Coralline algae" },
    { q: "Sea Cucumber scientific name (Sandfish)?", opts: ["Holothuria scabra", "Stichopus horrens", "Actinopyga lecanora", "Bohadschia marmorata"], a: "Holothuria scabra" },
    { q: "Value added product from Sea Cucumber?", opts: ["Trepang / Beche-de-mer", "Sashimi", "Caviar", "Fillet"], a: "Trepang / Beche-de-mer" },
    { q: "Sea Urchin gonad is called?", opts: ["Roe / Uni", "Milt", "Liver", "Intestine"], a: "Roe / Uni" },
    { q: "Sea Urchin scientific name (common)?", opts: ["Tripneustes gratilla", "Diadema setosum", "Echinothrix calamaris", "Acanthaster planci"], a: "Tripneustes gratilla" },
    { q: "Lobster commonly cultured in cages?", opts: ["Spiny Lobster (Panulirus)", "Claw Lobster (Homarus)", "Slipper Lobster", "Crayfish"], a: "Spiny Lobster (Panulirus)" },
    { q: "Main feed for cultured Lobsters?", opts: ["Trash fish / Mussels", "Pellets", "Phytoplankton", "Seaweed"], a: "Trash fish / Mussels" },
    { q: "Period when crustaceans replace shell?", opts: ["Molting", "Spawning", "Metamorphosis", "Hatching"], a: "Molting" },

    // --- NUTRITION (DIGESTION & METABOLISM) ---
    { q: "Enzyme breaking down Protein?", opts: ["Protease / Pepsin / Trypsin", "Amylase", "Lipase", "Cellulase"], a: "Protease / Pepsin / Trypsin" },
    { q: "Enzyme breaking down Starch/Carbs?", opts: ["Amylase", "Protease", "Lipase", "Pepsin"], a: "Amylase" },
    { q: "Enzyme breaking down Fats/Lipids?", opts: ["Lipase", "Amylase", "Trypsin", "Chymotrypsin"], a: "Lipase" },
    { q: "Stomach pH in carnivorous fish?", opts: ["Acidic (pH 2-4)", "Neutral", "Alkaline", "Basic"], a: "Acidic (pH 2-4)" },
    { q: "Fish lacking a true stomach?", opts: ["Astatic (e.g., Carp/Goldfish)", "Tilapia", "Grouper", "Catfish"], a: "Astatic (e.g., Carp/Goldfish)" },
    { q: "Absorption of nutrients occurs mainly in?", opts: ["Intestine", "Stomach", "Esophagus", "Mouth"], a: "Intestine" },
    { q: "Structure increasing intestine surface area?", opts: ["Villi / Microvilli", "Cilia", "Flagella", "Scales"], a: "Villi / Microvilli" },
    { q: "Total energy in feed is called?", opts: ["Gross Energy (GE)", "Digestible Energy (DE)", "Metabolizable Energy (ME)", "Net Energy (NE)"], a: "Gross Energy (GE)" },
    { q: "Energy remaining after fecal loss?", opts: ["Digestible Energy (DE)", "Gross Energy", "Net Energy", "Heat Energy"], a: "Digestible Energy (DE)" },
    { q: "Basal Metabolism is energy for?", opts: ["Life maintenance at rest", "Swimming", "Growth", "Reproduction"], a: "Life maintenance at rest" },
    { q: "Non-Protein Nitrogen source for ruminants (not fish)?", opts: ["Urea", "Fish meal", "Soybean", "Corn"], a: "Urea" },
    { q: "Indispensable Amino Acids number?", opts: ["10", "20", "5", "2"], a: "10" },
    { q: "Water soluble vitamins?", opts: ["B-complex and C", "A, D, E, K", "A only", "D only"], a: "B-complex and C" },
    { q: "Fat soluble vitamins?", opts: ["A, D, E, K", "B and C", "B12", "Folic Acid"], a: "A, D, E, K" },
    { q: "Vitamin E deficiency causes?", opts: ["Muscular Dystrophy / Rancidity issues", "Scoliosis", "Blindness", "Hemorrhage"], a: "Muscular Dystrophy / Rancidity issues" },
    { q: "Vitamin A deficiency affects?", opts: ["Vision / Eyes", "Bones", "Blood clotting", "Digestion"], a: "Vision / Eyes" },
    { q: "Mineral for bone formation?", opts: ["Calcium / Phosphorus", "Iron", "Zinc", "Iodine"], a: "Calcium / Phosphorus" },
    { q: "Mineral in hemoglobin?", opts: ["Iron", "Copper", "Magnesium", "Sodium"], a: "Iron" },
    { q: "Mineral in hemocyanin (shrimp blood)?", opts: ["Copper", "Iron", "Zinc", "Calcium"], a: "Copper" },
    { q: "Deficiency of Iodine causes?", opts: ["Goiter", "Anemia", "Rickets", "Scurvy"], a: "Goiter" },

    // --- AQUACULTURE ENGINEERING (Part 3) ---
    { q: "Volume of a circular tank?", opts: ["V = πr²h", "V = L x W x H", "V = 0.5 bh", "V = 2πr"], a: "V = πr²h" },
    { q: "1 Cubic meter (m3) equals how many liters?", opts: ["1000 Liters", "100 Liters", "10 Liters", "10,000 Liters"], a: "1000 Liters" },
    { q: "1 Gallon is approx how many liters?", opts: ["3.785 Liters", "1 Liter", "5 Liters", "10 Liters"], a: "3.785 Liters" },
    { q: "1 Hectare equals how many sq meters?", opts: ["10,000 m2", "1,000 m2", "100 m2", "100,000 m2"], a: "10,000 m2" },
    { q: "Slope 100% is equivalent to?", opts: ["45 degrees", "90 degrees", "10 degrees", "30 degrees"], a: "45 degrees" },
    { q: "Surveying tool for elevation?", opts: ["Transit / Theodolite / Level", "Compass", "Tape measure", "Protractor"], a: "Transit / Theodolite / Level" },
    { q: "Bench Mark (BM) in survey means?", opts: ["Reference point of known elevation", "A seat", "A mark on a tree", "Corner of pond"], a: "Reference point of known elevation" },
    { q: "Cut and Fill method is for?", opts: ["Earthwork balancing", "Feeding", "Harvesting", "Water change"], a: "Earthwork balancing" },
    { q: "Shrinkage factor for clay soil?", opts: ["10-20%", "0%", "50%", "100%"], a: "10-20%" },
    { q: "Freeboard allowance for wave action?", opts: ["0.3 - 0.6 m", "0 m", "2 m", "10 m"], a: "0.3 - 0.6 m" },
    { q: "Fetch refers to?", opts: ["Distance wind travels across water", "Retrieving a dog", "Depth of pond", "Width of dike"], a: "Distance wind travels across water" },
    { q: "Riprap is used for?", opts: ["Erosion control", "Fertilizer", "Fish shelter", "Feeding"], a: "Erosion control" },
    { q: "Most durable material for seawater pipe?", opts: ["HDPE / PVC", "Steel", "Iron", "Copper"], a: "HDPE / PVC" },
    { q: "Head loss in pipes is caused by?", opts: ["Friction", "Gravity", "Pressure", "Heat"], a: "Friction" },
    { q: "Elbows and valves cause?", opts: ["Minor losses (Head loss)", "Gain in pressure", "More flow", "Cooling"], a: "Minor losses (Head loss)" },
    { q: "Cavitation in pumps causes?", opts: ["Damage to impeller", "Better flow", "Less noise", "Higher pressure"], a: "Damage to impeller" },
    { q: "Net Positive Suction Head (NPSH) relates to?", opts: ["Pump suction preventing cavitation", "Discharge head", "Pipe length", "Motor speed"], a: "Pump suction preventing cavitation" },
    { q: "Aerator moving water into air?", opts: ["Splash / Paddlewheel", "Diffuser", "Airlift", "Propeller"], a: "Splash / Paddlewheel" },
    { q: "Aerator injecting air into water?", opts: ["Blower / Diffuser", "Paddlewheel", "Vertical pump", "Spray"], a: "Blower / Diffuser" },
    { q: "Efficiency of aerator measured in?", opts: ["SAE (Standard Aeration Efficiency)", "HP", "RPM", "Volts"], a: "SAE (Standard Aeration Efficiency)" },
  // --- BATCH 4: QUESTIONS 301-400 ---
    // --- LIVE FEEDS & PLANKTON CULTURE ---
    { q: "Fertilizer stimulating Diatom growth?", opts: ["Silicate / Urea", "Potash", "Lime", "Manure only"], a: "Silicate / Urea" },
    { q: "Microalgae used for Rotifer culture?", opts: ["Nannochloropsis", "Sargassum", "Gracilaria", "Kappaphycus"], a: "Nannochloropsis" },
    { q: "Diatom with a silica shell is called?", opts: ["Frustule", "Capsule", "Spore", "Cyst"], a: "Frustule" },
    { q: "Skeletonema costatum is a?", opts: ["Diatom", "Dinoflagellate", "Green Algae", "Blue-green Algae"], a: "Diatom" },
    { q: "Tetraselmis sp. is classified as?", opts: ["Green Algae", "Red Algae", "Brown Algae", "Diatom"], a: "Green Algae" },
    { q: "Spirulina (Arthrospira) is a?", opts: ["Blue-green Algae (Cyanobacteria)", "Green Algae", "Diatom", "Fungus"], a: "Blue-green Algae (Cyanobacteria)" },
    { q: "Nutrient content Spirulina is famous for?", opts: ["High Protein (60-70%)", "High Fat", "High Calcium", "High Fiber"], a: "High Protein (60-70%)" },
    { q: "Benthic algae complex in ponds?", opts: ["Lab-lab", "Lumut", "Plankton", "Seaweed"], a: "Lab-lab" },
    { q: "Filamentous green algae complex?", opts: ["Lumut", "Lab-lab", "Diatoms", "Phytoplankton"], a: "Lumut" },
    { q: "Dominant species in Lumut?", opts: ["Enteromorpha / Chaetomorpha", "Nitzschia", "Chlorella", "Skeletonema"], a: "Enteromorpha / Chaetomorpha" },
    { q: "Process of removing Artemia shells?", opts: ["Decapsulation", "Hatching", "Enrichment", "Disinfection"], a: "Decapsulation" },
    { q: "Chemical used for decapsulation?", opts: ["Hypochlorite (Bleach)", "Formalin", "Alcohol", "Acid"], a: "Hypochlorite (Bleach)" },
    { q: "Moina is also known as?", opts: ["Water flea (Cladoceran)", "Rotifer", "Copepod", "Shrimp"], a: "Water flea (Cladoceran)" },
    { q: "Daphnia is a?", opts: ["Cladoceran", "Rotifer", "Protozoan", "Fish"], a: "Cladoceran" },
    { q: "Life span of Rotifers?", opts: ["Short (few days)", "1 year", "1 month", "1 hour"], a: "Short (few days)" },
    { q: "Standard density for Chlorella culture?", opts: ["1-3 million cells/ml", "100 cells/ml", "1 billion cells/ml", "10 cells/ml"], a: "1-3 million cells/ml" },
    { q: "Counting chamber for phytoplankton?", opts: ["Hemocytometer", "Sedgwick-Rafter", "Beaker", "Ruler"], a: "Hemocytometer" },
    { q: "Counting chamber for zooplankton?", opts: ["Sedgwick-Rafter", "Hemocytometer", "Test tube", "Spectrophotometer"], a: "Sedgwick-Rafter" },
    { q: "Phase of algae growth for harvest?", opts: ["Exponential / Log phase", "Lag phase", "Death phase", "Stationary phase"], a: "Exponential / Log phase" },
    { q: "Term for crashing of algal culture?", opts: ["Collapse", "Bloom", "Growth", "Spawning"], a: "Collapse" },

    // --- SHRIMP & CRUSTACEAN HEALTH (ADVANCED) ---
    { q: "MBV affects which organ in shrimp?", opts: ["Hepatopancreas", "Gills", "Muscle", "Eyes"], a: "Hepatopancreas" },
    { q: "IHHNV causes what deformity?", opts: ["Runt Deformity Syndrome (RDS)", "White spots", "Black gills", "Soft shell"], a: "Runt Deformity Syndrome (RDS)" },
    { q: "Taura Syndrome Virus (TSV) origin?", opts: ["Americas / Ecuador", "Asia", "Europe", "Africa"], a: "Americas / Ecuador" },
    { q: "Yellow Head Virus (YHV) target?", opts: ["Gills and Hepatopancreas", "Tail", "Legs", "Antenna"], a: "Gills and Hepatopancreas" },
    { q: "Loose Shell Syndrome is caused by?", opts: ["Poor nutrition / Bacteria", "Virus", "Fungus", "Genetics"], a: "Poor nutrition / Bacteria" },
    { q: "Black Gill Disease cause?", opts: ["Soil accumulation / Fusarium / Bacteria", "Virus", "Sunlight", "Feed"], a: "Soil accumulation / Fusarium / Bacteria" },
    { q: "Muscle Necrosis (White muscle) cause?", opts: ["Stress / Low DO / Temperature shock", "Virus", "Parasite", "Fungus"], a: "Stress / Low DO / Temperature shock" },
    { q: "Soft Shelling (persistent) cause?", opts: ["Low Phosphate / Nutrition", "Virus", "High Calcium", "High Salinity"], a: "Low Phosphate / Nutrition" },
    { q: "Cramped tail muscle cause?", opts: ["Temperature shock", "Virus", "Bacteria", "Fungus"], a: "Temperature shock" },
    { q: "Epicommensals on shrimp shell?", opts: ["Zoothamnium / Vorticella", "Vibrio", "WSSV", "YHV"], a: "Zoothamnium / Vorticella" },
    { q: "Treatment for Zoothamnium?", opts: ["Formalin bath", "Antibiotic", "Vitamin C", "Probiotic"], a: "Formalin bath" },
    { q: "Microsporidian affecting shrimp?", opts: ["Enterocytozoon hepatopenaei (EHP)", "WSSV", "Vibrio", "Ich"], a: "Enterocytozoon hepatopenaei (EHP)" },
    { q: "Symptom of EHP?", opts: ["Slow growth / Variation in size", "White spots", "Red body", "Mortality"], a: "Slow growth / Variation in size" },
    { q: "SPF stands for?", opts: ["Specific Pathogen Free", "Sun Protection Factor", "Shrimp Prawn Fish", "Standard Pond Formula"], a: "Specific Pathogen Free" },
    { q: "SPR stands for?", opts: ["Specific Pathogen Resistant", "Specific Pathogen Rare", "Standard Prawn Rate", "Shrimp Pond Ready"], a: "Specific Pathogen Resistant" },
    { q: "Hemolymph is?", opts: ["Shrimp blood", "Shrimp feed", "Shrimp waste", "Shrimp egg"], a: "Shrimp blood" },
    { q: "Phagocytosis is?", opts: ["Cell eating bacteria", "Cell division", "Cell death", "Cell movement"], a: "Cell eating bacteria" },
    { q: "Melanization in shrimp is?", opts: ["Darkening / Immune response", "Whitening", "Molting", "Breeding"], a: "Darkening / Immune response" },
    { q: "Lymphoid organ in shrimp functions for?", opts: ["Filtering bacteria / Immunity", "Digestion", "Reproduction", "Vision"], a: "Filtering bacteria / Immunity" },
    { q: "Best way to detect carriers of WSSV?", opts: ["PCR Test", "Visual check", "Smell", "Touch"], a: "PCR Test" },

    // --- FINFISH HEALTH & TREATMENTS ---
    { q: "Columnaris disease is caused by?", opts: ["Flavobacterium columnare", "Aeromonas", "Vibrio", "Streptococcus"], a: "Flavobacterium columnare" },
    { q: "Symptom of Columnaris?", opts: ["Saddleback lesion / Fin erosion", "Pop-eye", "Bloat", "White spots"], a: "Saddleback lesion / Fin erosion" },
    { q: "Edwardsiella ictaluri causes?", opts: ["Enteric Septicemia of Catfish", "Vibriosis", "Motile Aeromonas", "Ich"], a: "Enteric Septicemia of Catfish" },
    { q: "Motile Aeromonas Septicemia agent?", opts: ["Aeromonas hydrophila", "Vibrio harveyi", "E. coli", "Salmonella"], a: "Aeromonas hydrophila" },
    { q: "Streptococcosis symptom?", opts: ["Exophthalmia (Pop-eye) / Erratic swimming", "White spots", "Ulcers", "Fin rot"], a: "Exophthalmia (Pop-eye) / Erratic swimming" },
    { q: "Viral Hemorrhagic Septicemia (VHS) affects?", opts: ["Many marine/freshwater fish", "Shrimp only", "Crabs only", "Plants"], a: "Many marine/freshwater fish" },
    { q: "Spring Viremia of Carp (SVC) cause?", opts: ["Rhabdovirus", "Herpesvirus", "Iridovirus", "Bacteria"], a: "Rhabdovirus" },
    { q: "Koi Herpes Virus (KHV) affects?", opts: ["Koi and Common Carp", "Tilapia", "Goldfish", "Catfish"], a: "Koi and Common Carp" },
    { q: "Epizootic Ulcerative Syndrome (EUS) cause?", opts: ["Aphanomyces invadans (Fungus)", "Virus", "Bacteria", "Worm"], a: "Aphanomyces invadans (Fungus)" },
    { q: "Velvet disease is caused by?", opts: ["Oodinium / Piscinoodinium", "Ich", "Trichodina", "Lerneae"], a: "Oodinium / Piscinoodinium" },
    { q: "Gold dust appearance on fish?", opts: ["Velvet Disease", "Ich", "Fungus", "Bacterial"], a: "Velvet Disease" },
    { q: "Monogenean parasite on gills?", opts: ["Dactylogyrus", "Gyrodactylus", "Argulus", "Lerneae"], a: "Dactylogyrus" },
    { q: "Monogenean parasite on skin?", opts: ["Gyrodactylus", "Dactylogyrus", "Ich", "Oodinium"], a: "Gyrodactylus" },
    { q: "Treatment for Monogeneans?", opts: ["Praziquantel / Formalin", "Antibiotic", "Vitamin", "Probiotic"], a: "Praziquantel / Formalin" },
    { q: "Tapeworms are?", opts: ["Cestodes", "Nematodes", "Trematodes", "Protozoa"], a: "Cestodes" },
    { q: "Roundworms are?", opts: ["Nematodes", "Cestodes", "Trematodes", "Flukes"], a: "Nematodes" },
    { q: "Grubs (Yellow/White) are?", opts: ["Trematode larvae (Digenea)", "Nematodes", "Bacteria", "Viruses"], a: "Trematode larvae (Digenea)" },
    { q: "Intermediate host of Digenean trematodes?", opts: ["Snails", "Birds", "Fish", "Humans"], a: "Snails" },
    { q: "Anisakis is a?", opts: ["Nematode (danger to humans)", "Cestode", "Bacteria", "Fungus"], a: "Nematode (danger to humans)" },
    { q: "Effective disinfection method for nets?", opts: ["Drying / Chlorine dip", "Washing with water", "Freezing", "Heating"], a: "Drying / Chlorine dip" },

    // --- WATER QUALITY CALCULATIONS & CONCEPTS ---
    { q: "Molecular weight of Ammonia (NH3)?", opts: ["17 g/mol", "14 g/mol", "1 g/mol", "44 g/mol"], a: "17 g/mol" },
    { q: "Atomic weight of Nitrogen (N)?", opts: ["14", "1", "16", "12"], a: "14" },
    { q: "Converting NH3-N to NH3 multiply by?", opts: ["1.21", "1.0", "0.5", "2.0"], a: "1.21" },
    { q: "Oxygen saturation decreases when?", opts: ["Temp increases / Salinity increases", "Temp decreases", "Salinity decreases", "Pressure increases"], a: "Temp increases / Salinity increases" },
    { q: "Highest density of water is at?", opts: ["4°C", "0°C", "100°C", "25°C"], a: "4°C" },
    { q: "Standard Biological Oxygen Demand test days?", opts: ["5 days (BOD5)", "1 day", "10 days", "30 days"], a: "5 days (BOD5)" },
    { q: "TAN stands for?", opts: ["Total Ammonia Nitrogen", "Total Available Nutrients", "Toxic Ammonia Nitrogen", "Temperature and Nitrate"], a: "Total Ammonia Nitrogen" },
    { q: "Ideally, nitrite (NO2) should be?", opts: ["0 ppm", "10 ppm", "5 ppm", "1 ppm"], a: "0 ppm" },
    { q: "Which is more toxic: NO2 or NO3?", opts: ["NO2 (Nitrite)", "NO3 (Nitrate)", "Same", "Neither"], a: "NO2 (Nitrite)" },
    { q: "Chloride protects fish from?", opts: ["Nitrite toxicity", "Ammonia toxicity", "pH shock", "Heat"], a: "Nitrite toxicity" },
    { q: "Blue baby syndrome is caused by?", opts: ["High Nitrate in drinking water", "Ammonia", "Nitrite", "Lead"], a: "High Nitrate in drinking water" },
    { q: "Langlier Saturation Index relates to?", opts: ["Calcium carbonate scaling", "Oxygen saturation", "Algae growth", "Fish growth"], a: "Calcium carbonate scaling" },
    { q: "Water hardness unit?", opts: ["mg/L as CaCO3", "mg/L as NaCl", "ppm N", "ppt"], a: "mg/L as CaCO3" },
    { q: "Soft water has hardness?", opts: ["0-60 mg/L", "100-200 mg/L", ">200 mg/L", "1000 mg/L"], a: "0-60 mg/L" },
    { q: "Liming material with highest Neutralizing Value?", opts: ["Quicklime (CaO) ~179%", "Ag Lime", "Hydrated Lime", "Dolomite"], a: "Quicklime (CaO) ~179%" },
    { q: "Neutralizing value of CaCO3?", opts: ["100%", "179%", "135%", "50%"], a: "100%" },
    { q: "Nutrient usually limiting in freshwater?", opts: ["Phosphorus", "Nitrogen", "Potassium", "Carbon"], a: "Phosphorus" },
    { q: "Nutrient usually limiting in seawater?", opts: ["Nitrogen", "Phosphorus", "Iron", "Silicon"], a: "Nitrogen" },
    { q: "Redfield Ratio (C:N:P) in plankton?", opts: ["106:16:1", "1:1:1", "50:10:1", "100:100:1"], a: "106:16:1" },
    { q: "Alum (Aluminum Sulfate) is used to?", opts: ["Flocculate clay particles / Clear water", "Fertilize", "Raise pH", "Kill fish"], a: "Flocculate clay particles / Clear water" },

    // --- AQUACULTURE LAWS & REGULATIONS (PH) ---
    { q: "FAO 214 covers?", opts: ["Code of Practice for Aquaculture", "Trawl Fishing", "Importation", "Tuna"], a: "Code of Practice for Aquaculture" },
    { q: "Standard ban on antibiotics includes?", opts: ["Chloramphenicol / Nitrofuran", "Oxytetracycline", "Erythromycin", "Amoxicillin"], a: "Chloramphenicol / Nitrofuran" },
    { q: "Malachite Green is?", opts: ["Banned carcinogenic dye", "Approved medication", "Fertilizer", "Fish feed"], a: "Banned carcinogenic dye" },
    { q: "Maximum residue limit (MRL) refers to?", opts: ["Allowed chemical in meat", "Feed rate", "Stocking density", "Harvest size"], a: "Allowed chemical in meat" },
    { q: "Authority regulating aquaculture drugs?", opts: ["BFAR / FDA", "DENR", "DOH", "DTI"], a: "BFAR / FDA" },
    { q: "Aquatic Wildlife is under jurisdiction of?", opts: ["DA-BFAR (mostly)", "DENR (Marine Turtles/Mammals)", "DILG", "DOT"], a: "DA-BFAR (mostly)" },
    { q: "Importation of live fish requires?", opts: ["Permit from BFAR", "Permit from Mayor", "No permit", "Customs only"], a: "Permit from BFAR" },
    { q: "Introducing exotic species without permit is?", opts: ["Illegal", "Allowed", "Encouraged", "Ignored"], a: "Illegal" },
    { q: "FLA stands for?", opts: ["Fishpond Lease Agreement", "Fishing License Area", "Farm Land Area", "Fish Law Act"], a: "Fishpond Lease Agreement" },
    { q: "Duration of FLA?", opts: ["25 years renewable for 25", "50 years fixed", "10 years", "100 years"], a: "25 years renewable for 25" },
];
