// capture.js
// Part 2 of 4: Capture Fisheries Board Exam Review Questions
// Topics: Gear Design, Methods, Navigation, Seamanship, Laws (RA 10654)

const captureQuestions = [
    // --- FISHING GEAR CLASSIFICATION & DESIGN ---
    { q: "Which is an Active Gear?", opts: ["Trawl", "Gill net", "Fish pot", "Longline"], a: "Trawl" },
    { q: "Which is a Passive Gear?", opts: ["Gill net", "Purse seine", "Trawl", "Ring net"], a: "Gill net" },
    { q: "Mesh size is measured by?", opts: ["Knot to knot (stretched)", "Diagonal", "Area", "Diameter"], a: "Knot to knot (stretched)" },
    { q: "Closes the bottom of a purse seine?", opts: ["Purse line", "Float line", "Lead line", "Bunt"], a: "Purse line" },
    { q: "Most common gear for catching Tuna?", opts: ["Purse Seine / Handline", "Trawl", "Push net", "Beach seine"], a: "Purse Seine / Handline" },
    { q: "Hanging ratio 'E' generally used for gillnets?", opts: ["0.3 - 0.5", "0.9", "1.0", "0.1"], a: "0.3 - 0.5" },
    { q: "Twine size '210d/9' means?", opts: ["210 denier, 9 ply", "9 denier, 210 ply", "9mm thick", "210kg strength"], a: "210 denier, 9 ply" },
    { q: "Device to keep trawl mouth open horizontally?", opts: ["Otter Boards", "Floats", "Sinkers", "Beams"], a: "Otter Boards" },
    { q: "Net consisting of three layers?", opts: ["Trammel net", "Gill net", "Cast net", "Dip net"], a: "Trammel net" },
    { q: "Part of the hook that prevents escape?", opts: ["Barb", "Eye", "Shank", "Gap"], a: "Barb" },
    { q: "Danish Seine is locally known as?", opts: ["Hulbot-hulbot (modified)", "Zipper", "Superlight", "Baling"], a: "Hulbot-hulbot (modified)" },
    { q: "Gear that encircles a school of fish?", opts: ["Purse Seine", "Gill net", "Longline", "Trawl"], a: "Purse Seine" },
    { q: "Vertical line with baited hooks?", opts: ["Handline / Drop line", "Longline", "Trotline", "Troll line"], a: "Handline / Drop line" },
    { q: "Horizontal line with snoods and hooks?", opts: ["Longline", "Handline", "Pole and line", "Jig"], a: "Longline" },
    { q: "Fish pot for crabs is called?", opts: ["Bubo", "Salambao", "Sakag", "Pukot"], a: "Bubo" },
    { q: "Light used to attract fish?", opts: ["Superlight", "Spotlight", "Flashlight", "Headlight"], a: "Superlight" },
    { q: "Payao is a type of?", opts: ["FAD (Fish Aggregating Device)", "Net", "Boat", "Sonar"], a: "FAD (Fish Aggregating Device)" },
    { q: "Illegal fishing method using rocks?", opts: ["Muro-ami", "Pa-aling", "Kayakas", "Sodium"], a: "Muro-ami" },
    { q: "Pa-aling uses what to drive fish?", opts: ["Bubbles / Air", "Rocks", "Dynamite", "Electricity"], a: "Bubbles / Air" },
    { q: "Knot used to join ropes of different sizes?", opts: ["Sheet bend", "Reef knot", "Bowline", "Clove hitch"], a: "Sheet bend" },
    { q: "Knot that does not slip/jam, makes a loop?", opts: ["Bowline", "Reef knot", "Sheepshank", "Overhand"], a: "Bowline" },
    { q: "Yarn numbering system: Denier is?", opts: ["Weight in grams of 9000m", "Length of 1kg", "Diameter in mm", "Break strength"], a: "Weight in grams of 9000m" },
    { q: "Yarn numbering: Tex is?", opts: ["Weight in grams of 1000m", "Weight of 9000m", "Length of 1lb", "Ply count"], a: "Weight in grams of 1000m" },
    { q: "Main material for modern nets?", opts: ["Polyamide (Nylon)", "Cotton", "Abaca", "Silk"], a: "Polyamide (Nylon)" },
    { q: "PE rope floats because specific gravity is?", opts: ["< 1.0 (approx 0.95)", "> 1.0", "Equal to 1", "Very heavy"], a: "< 1.0 (approx 0.95)" },

    // --- NAVIGATION & SEAMANSHIP ---
    { q: "Starboard refers to?", opts: ["Right side", "Left side", "Rear", "Front"], a: "Right side" },
    { q: "Port refers to?", opts: ["Left side", "Right side", "Rear", "Front"], a: "Left side" },
    { q: "Light color for Starboard side?", opts: ["Green", "Red", "White", "Yellow"], a: "Green" },
    { q: "Light color for Port side?", opts: ["Red", "Green", "White", "Yellow"], a: "Red" },
    { q: "Stern is the?", opts: ["Rear of the boat", "Front", "Side", "Bottom"], a: "Rear of the boat" },
    { q: "Bow is the?", opts: ["Front of the boat", "Rear", "Side", "Deck"], a: "Front of the boat" },
    { q: "Side protected from the wind?", opts: ["Leeward", "Windward", "Port", "Starboard"], a: "Leeward" },
    { q: "Side facing the wind?", opts: ["Windward", "Leeward", "Aft", "Forward"], a: "Windward" },
    { q: "Unit of speed at sea?", opts: ["Knot", "Kph", "Mph", "Mach"], a: "Knot" },
    { q: "1 Knot is equal to?", opts: ["1 Nautical Mile per hour", "1.6 km/h", "1 Mile per hour", "100 m/s"], a: "1 Nautical Mile per hour" },
    { q: "1 Nautical Mile in meters?", opts: ["1852 meters", "1000 meters", "1609 meters", "5280 meters"], a: "1852 meters" },
    { q: "Device measuring depth using sound?", opts: ["Echo Sounder / Fish Finder", "Radar", "GPS", "Compass"], a: "Echo Sounder / Fish Finder" },
    { q: "Device for location (Lat/Long)?", opts: ["GPS", "VMS", "Sonar", "Radio"], a: "GPS" },
    { q: "VMS stands for?", opts: ["Vessel Monitoring System", "Very Marine Ship", "Visual Map System", "Voltage Meter"], a: "Vessel Monitoring System" },
    { q: "Radar uses?", opts: ["Radio waves", "Sound waves", "Light", "Magnetism"], a: "Radio waves" },
    { q: "Sonar stands for?", opts: ["Sound Navigation and Ranging", "Solar Navigation", "Sonic Radar", "Sound Area"], a: "Sound Navigation and Ranging" },
    { q: "Latitude lines are?", opts: ["Parallel to Equator", "Vertical", "Converge at poles", "Magnetic"], a: "Parallel to Equator" },
    { q: "Longitude lines meet at?", opts: ["The Poles", "The Equator", "Greenwich", "Nowhere"], a: "The Poles" },
    { q: "Prime Meridian is at?", opts: ["0 degrees Longitude", "0 degrees Latitude", "180 degrees", "90 degrees"], a: "0 degrees Longitude" },
    { q: "International Date Line is approx?", opts: ["180 degrees Longitude", "0 degrees", "90 degrees", "45 degrees"], a: "180 degrees Longitude" },
    { q: "Bearing 090 degrees is?", opts: ["East", "North", "South", "West"], a: "East" },
    { q: "Bearing 270 degrees is?", opts: ["West", "East", "North", "South"], a: "West" },
    { q: "Device to measure atmospheric pressure?", opts: ["Barometer", "Anemometer", "Thermometer", "Hygrometer"], a: "Barometer" },
    { q: "Colreg Rule: Overtaking vessel must?", opts: ["Keep out of the way", "Maintain course", "Speed up", "Honk"], a: "Keep out of the way" },
    { q: "Vessel 'Not under command' lights?", opts: ["Red over Red (All round)", "White over White", "Green over Green", "Red over White"], a: "Red over Red (All round)" },

    // --- FISHERIES LAWS & REGULATIONS (RA 8550 / RA 10654) ---
    { q: "The Philippine Fisheries Code of 1998?", opts: ["RA 8550", "RA 10654", "PD 704", "RA 9147"], a: "RA 8550" },
    { q: "Law amending RA 8550 (IUUF law)?", opts: ["RA 10654", "RA 8550", "RA 7160", "EO 26"], a: "RA 10654" },
    { q: "Municipal waters distance?", opts: ["15 km from shoreline", "7 km", "10 km", "200 miles"], a: "15 km from shoreline" },
    { q: "Exclusive Economic Zone (EEZ) distance?", opts: ["200 Nautical Miles", "12 Nautical Miles", "100 km", "1000 miles"], a: "200 Nautical Miles" },
    { q: "Territorial Sea distance?", opts: ["12 Nautical Miles", "24 Nautical Miles", "200 Nautical Miles", "3 miles"], a: "12 Nautical Miles" },
    { q: "Commercial fishing is allowed in?", opts: ["Beyond 15 km (Municipal)", "Inside 15 km", "Rivers", "Mangroves"], a: "Beyond 15 km (Municipal)" },
    { q: "Small Scale Commercial Fishing tonnage?", opts: ["3.1 to 20 GT", "1.1 to 3 GT", "20.1 to 150 GT", "> 150 GT"], a: "3.1 to 20 GT" },
    { q: "Medium Scale Commercial Fishing tonnage?", opts: ["20.1 to 150 GT", "3.1 to 20 GT", "> 150 GT", "< 3 GT"], a: "20.1 to 150 GT" },
    { q: "Large Scale Commercial Fishing tonnage?", opts: ["> 150 GT", "20 to 100 GT", "500 GT", "1000 GT"], a: "> 150 GT" },
    { q: "Municipal fishing utilizes vessels of?", opts: ["3 GT or less", "3.1 to 10 GT", "Any size", "No boat"], a: "3 GT or less" },
    { q: "Jurisdiction over Municipal waters?", opts: ["LGU / City / Municipality", "BFAR", "Coast Guard", "Navy"], a: "LGU / City / Municipality" },
    { q: "Who issues Commercial Fishing Licenses?", opts: ["BFAR", "LGU", "MARINA", "DTI"], a: "BFAR" },
    { q: "Registration of fishing boats (3GT below)?", opts: ["LGU", "MARINA", "BFAR", "Coast Guard"], a: "LGU" },
    { q: "Using explosives for fishing is?", opts: ["Illegal", "Regulated", "Allowed for research", "Traditional"], a: "Illegal" },
    { q: "Fine for poaching (Foreign entry)?", opts: ["$600k - $1M (USD)", "P500", "P10,000", "Imprisonment only"], a: "$600k - $1M (USD)" },
    { q: "Closed season is implemented for?", opts: ["Spawning / Conservation", "Vessel repair", "Holidays", "Tourism"], a: "Spawning / Conservation" },
    { q: "Catching Sabalo (Breeder Bangus) is?", opts: ["Illegal / Prohibited", "Allowed", "Regulated", "Encouraged"], a: "Illegal / Prohibited" },
    { q: "Cutting shark fins and discarding body?", opts: ["Finning (Illegal)", "Processing", "Cleaning", "Harvesting"], a: "Finning (Illegal)" },
    { q: "IUUF stands for?", opts: ["Illegal, Unreported, Unregulated Fishing", "International Union for Underwater Fishing", "Inter-agency Unit for Fishing", "Integrated Urban Farming"], a: "Illegal, Unreported, Unregulated Fishing" },
    { q: "Ban on Muro-ami excludes?", opts: ["Pa-aling (regulated)", "Dynamite", "Cyanide", "Electro-fishing"], a: "Pa-aling (regulated)" },
    { q: "Minimum mesh size for Pa-aling?", opts: ["3.38 cm", "2 cm", "5 cm", "10 cm"], a: "3.38 cm" },
    { q: "Coral exportation is?", opts: ["Prohibited", "Allowed with tax", "Allowed for souvenir", "Regulated"], a: "Prohibited" },
    { q: "Mangrove conversion to fishpond is?", opts: ["Prohibited (since 1998)", "Allowed", "Encouraged", "Subsidized"], a: "Prohibited (since 1998)" },
    { q: "Distance from shore for 'Active Gear' ban?", opts: ["Inside Municipal Waters (15km)", "Inside 5km", "Open sea", "None"], a: "Inside Municipal Waters (15km)" },

    // --- FISHERIES BIOLOGY & MANAGEMENT ---
    { q: "CPUE stands for?", opts: ["Catch Per Unit Effort", "Catch Per Underwater Event", "Cost Per Unit Energy", "Catch Processing Unit"], a: "Catch Per Unit Effort" },
    { q: "MSY stands for?", opts: ["Maximum Sustainable Yield", "Mean Sustainable Year", "Maximum Size Yield", "Minimum Safe Yield"], a: "Maximum Sustainable Yield" },
    { q: "Condition where catch exceeds MSY?", opts: ["Overfishing", "Underfishing", "Optimization", "Growth"], a: "Overfishing" },
    { q: "Growth overfishing means?", opts: ["Catching fish before they grow/reproduce", "Catching too many adults", "Destroying habitat", "Pollution"], a: "Catching fish before they grow/reproduce" },
    { q: "Recruitment overfishing means?", opts: ["Parent stock reduced too low to reproduce", "Catching small fish", "Using dynamite", "Using trawl"], a: "Parent stock reduced too low to reproduce" },
    { q: "Fish migrating River to Sea to spawn?", opts: ["Catadromous", "Anadromous", "Oceanodromous", "Potamodromous"], a: "Catadromous" },
    { q: "Fish migrating Sea to River to spawn?", opts: ["Anadromous", "Catadromous", "Amphidromous", "Limnodromous"], a: "Anadromous" },
    { q: "Example of Catadromous fish?", opts: ["Eel (Anguilla)", "Salmon", "Tuna", "Tilapia"], a: "Eel (Anguilla)" },
    { q: "Example of Anadromous fish?", opts: ["Salmon", "Eel", "Grouper", "Milkfish"], a: "Salmon" },
    { q: "Fish migrating purely within ocean?", opts: ["Oceanodromous", "Potamodromous", "Diadromous", "Sedentary"], a: "Oceanodromous" },
    { q: "Example of Oceanodromous fish?", opts: ["Skipjack Tuna", "Tilapia", "Carp", "Catfish"], a: "Skipjack Tuna" },
    { q: "Skipjack Tuna scientific name?", opts: ["Katsuwonus pelamis", "Thunnus albacares", "Thunnus obesus", "Auxis rochei"], a: "Katsuwonus pelamis" },
    { q: "Yellowfin Tuna scientific name?", opts: ["Thunnus albacares", "Katsuwonus pelamis", "Thunnus thynnus", "Sarda sarda"], a: "Thunnus albacares" },
    { q: "Bigeye Tuna scientific name?", opts: ["Thunnus obesus", "Thunnus tonggol", "Katsuwonus pelamis", "Auxis thazard"], a: "Thunnus obesus" },
    { q: "Sardine species (Tamban)?", opts: ["Sardinella lemuru", "Chanos chanos", "Rastrelliger kanagurta", "Decapterus macarellus"], a: "Sardinella lemuru" },
    { q: "Round Scad (Galunggong) scientific name?", opts: ["Decapterus macrosoma / macarellus", "Selar crumenophthalmus", "Rastrelliger brachysoma", "Stolephorus"], a: "Decapterus macrosoma / macarellus" },
    { q: "Ghost fishing refers to?", opts: ["Lost gear continuing to catch fish", "Fishing at night", "Fishing spirits", "Invisible nets"], a: "Lost gear continuing to catch fish" },
    { q: "By-catch refers to?", opts: ["Non-target species caught", "Main catch", "Trash fish", "Best fish"], a: "Non-target species caught" },
    { q: "TED in trawls stands for?", opts: ["Turtle Excluder Device", "Trawl Efficiency Device", "Total Energy Device", "Target Eliminator"], a: "Turtle Excluder Device" },
    { q: "JTED stands for?", opts: ["Juvenile and Trash Excluder Device", "Japan Trawl Device", "Joint Trawl Exclusion", "Jumbo Ted"], a: "Juvenile and Trash Excluder Device" },
  // --- BATCH 2: QUESTIONS 101-200 ---
    // --- ADVANCED GEAR TECHNOLOGY ---
    { q: "Hanging Ratio (E) formula?", opts: ["Length of Rope / Length of Stretched Netting", "Length of Net / Length of Rope", "Height / Width", "Weight / Length"], a: "Length of Rope / Length of Stretched Netting" },
    { q: "If E = 0.71, the mesh shape is?", opts: ["Square", "Diamond", "Flat", "Vertical"], a: "Square" },
    { q: "If E = 0.50, the mesh shape is?", opts: ["Diamond (standard)", "Square", "Flat", "Round"], a: "Diamond (standard)" },
    { q: "Amount of webbing gathered to make a bag?", opts: ["Bunt / Slack", "Hanging", "Selvage", "Mesh"], a: "Bunt / Slack" },
    { q: "Reinforced edge of a net?", opts: ["Selvage", "Gore", "Bunt", "Codend"], a: "Selvage" },
    { q: "Triangular section of netting to shape a trawl?", opts: ["Gore", "Selvage", "Codend", "Wing"], a: "Gore" },
    { q: "Back of the trawl where fish are collected?", opts: ["Codend", "Belly", "Wing", "Square"], a: "Codend" },
    { q: "Line connecting the trawl to the boat?", opts: ["Warp", "Bridle", "Sweep", "Headline"], a: "Warp" },
    { q: "Line between otter board and net wing?", opts: ["Bridle / Sweep", "Warp", "Lazy line", "Float line"], a: "Bridle / Sweep" },
    { q: "Correct cutting rate for a 'Normal' cut?", opts: ["1N (All bars)", "1T 1B", "1P 2M", "All points"], a: "1N (All bars)" },
    { q: "A 'Point' cut cuts?", opts: ["Two legs of a knot", "One leg", "Three legs", "The knot itself"], a: "Two legs of a knot" },
    { q: "A 'Mesh' cut cuts?", opts: ["Two legs (parallel)", "One leg", "The knot", "Sideways"], a: "Two legs (parallel)" },
    { q: "Specific gravity of Lead (Pb) sinkers?", opts: ["11.34", "7.8", "1.0", "2.5"], a: "11.34" },
    { q: "Specific gravity of Nylon (PA)?", opts: ["1.14 (Sinks)", "0.95", "1.38", "0.91"], a: "1.14 (Sinks)" },
    { q: "Specific gravity of Polyethylene (PE)?", opts: ["0.95 (Floats)", "1.14", "1.38", "1.0"], a: "0.95 (Floats)" },
    { q: "Specific gravity of Polyester (PES)?", opts: ["1.38 (Sinks)", "0.91", "1.14", "1.0"], a: "1.38 (Sinks)" },
    { q: "Synthetic fiber 'Kuralon' is?", opts: ["PVA (Polyvinyl Alcohol)", "PE", "PA", "PP"], a: "PVA (Polyvinyl Alcohol)" },
    { q: "Synthetic fiber 'Saran' is?", opts: ["PVDC", "PVC", "PE", "PA"], a: "PVDC" },
    { q: "Twine direction 'Z' twist?", opts: ["Right handed", "Left handed", "Neutral", "Braided"], a: "Right handed" },
    { q: "Twine direction 'S' twist?", opts: ["Left handed", "Right handed", "Neutral", "Crossed"], a: "Left handed" },
    { q: "Netting knot meant to slip/tighten (Bunt)?", opts: ["Bunt knot / Double sheet bend", "Reef knot", "Square knot", "Overhand"], a: "Bunt knot / Double sheet bend" },
    { q: "Breaking strength of wet nylon vs dry?", opts: ["Wet is weaker (loses ~10-15%)", "Wet is stronger", "Same", "Indeterminate"], a: "Wet is weaker (loses ~10-15%)" },
    { q: "Fishing gear using light and pump?", opts: ["Basnig (Lift net)", "Trawl", "Longline", "Gill net"], a: "Basnig (Lift net)" },
    { q: "Hook shape for Tuna Longline?", opts: ["Circle hook / J-hook with bent shank", "Straight J", "Treble hook", "Barbless"], a: "Circle hook / J-hook with bent shank" },
    { q: "Advantage of Circle hook?", opts: ["Reduces gut hooking / Turtle mortality", "Catches more trash fish", "Cheaper", "Easier to bait"], a: "Reduces gut hooking / Turtle mortality" },

    // --- NAVIGATION & STABILITY ---
    { q: "Vessel center of gravity (G) moves towards?", opts: ["Added weight", "Removed weight", "The keel", "The mast"], a: "Added weight" },
    { q: "Metacentric height (GM) is measure of?", opts: ["Initial stability", "Speed", "Fuel capacity", "Draft"], a: "Initial stability" },
    { q: "Positive GM means vessel is?", opts: ["Stable", "Unstable", "Neutral", "Sinking"], a: "Stable" },
    { q: "Device measuring magnetic north?", opts: ["Magnetic Compass", "Gyro Compass", "GPS", "Radar"], a: "Magnetic Compass" },
    { q: "Difference between True North and Magnetic North?", opts: ["Variation", "Deviation", "Leeway", "Drift"], a: "Variation" },
    { q: "Error in compass caused by ship's metal?", opts: ["Deviation", "Variation", "Declination", "Inclination"], a: "Deviation" },
    { q: "1 Minute of Latitude equals?", opts: ["1 Nautical Mile", "1 Kilometer", "100 Meters", "1 Degree"], a: "1 Nautical Mile" },
    { q: "Imaginary line of constant depth?", opts: ["Isobath / Contour", "Isotherm", "Isohaline", "Isobar"], a: "Isobath / Contour" },
    { q: "Navigation light: White masthead visibility?", opts: ["225 degrees", "360 degrees", "112.5 degrees", "135 degrees"], a: "225 degrees" },
    { q: "Navigation light: Sidelights visibility?", opts: ["112.5 degrees", "225 degrees", "360 degrees", "90 degrees"], a: "112.5 degrees" },
    { q: "Navigation light: Stern light visibility?", opts: ["135 degrees", "360 degrees", "112.5 degrees", "225 degrees"], a: "135 degrees" },
    { q: "Buoy System in the Philippines?", opts: ["IALA Region B", "IALA Region A", "US System", "EU System"], a: "IALA Region B" },
    { q: "IALA B: Returning from sea, Starboard buoy is?", opts: ["Red", "Green", "Yellow", "Black"], a: "Red" },
    { q: "Cardinal mark: Two cones pointing UP?", opts: ["North", "South", "East", "West"], a: "North" },
    { q: "Cardinal mark: Two cones pointing DOWN?", opts: ["South", "North", "East", "West"], a: "South" },
    { q: "Cardinal mark: Cones base-to-base?", opts: ["East", "West", "North", "South"], a: "East" },
    { q: "Sound signal: One short blast?", opts: ["Altering course to starboard", "Altering to port", "Astern", "Danger"], a: "Altering course to starboard" },
    { q: "Sound signal: Two short blasts?", opts: ["Altering course to port", "Starboard", "Astern", "Stop"], a: "Altering course to port" },
    { q: "Sound signal: Three short blasts?", opts: ["Operating astern propulsion", "Danger", "Pilot", "Towing"], a: "Operating astern propulsion" },
    { q: "Sound signal: Five short blasts?", opts: ["Danger / Doubt", "Passing", "Anchored", "Aground"], a: "Danger / Doubt" },

    // --- FISHERIES MANAGEMENT & BIOECONOMICS ---
    { q: "MEY stands for?", opts: ["Maximum Economic Yield", "Maximum Ecological Yield", "Mean Energy Yield", "Minimum Effort Yield"], a: "Maximum Economic Yield" },
    { q: "Relationship between MSY and MEY?", opts: ["MEY effort < MSY effort", "MEY > MSY", "MEY = MSY", "No relation"], a: "MEY effort < MSY effort" },
    { q: "Open Access fishery leads to?", opts: ["Tragedy of the Commons / Overfishing", "Sustainability", "High profits", "Conservation"], a: "Tragedy of the Commons / Overfishing" },
    { q: "Type of overfishing: Catching very small fish?", opts: ["Growth Overfishing", "Recruitment Overfishing", "Ecosystem Overfishing", "Economic Overfishing"], a: "Growth Overfishing" },
    { q: "Type of overfishing: Spawners are depleted?", opts: ["Recruitment Overfishing", "Growth Overfishing", "Malthusian", "Biological"], a: "Recruitment Overfishing" },
    { q: "Using dynamite leads to?", opts: ["Ecosystem Overfishing", "Growth Overfishing", "Economic Overfishing", "Sustainable Fishing"], a: "Ecosystem Overfishing" },
    { q: "Measure of abundance in stock assessment?", opts: ["CPUE", "Length", "Weight", "Color"], a: "CPUE" },
    { q: "Curve relating Effort to Yield?", opts: ["Schaefer Model / Parabola", "Linear", "Exponential", "Random"], a: "Schaefer Model / Parabola" },
    { q: "Total Allowable Catch (TAC) is?", opts: ["Limit on weight of fish caught", "Limit on boats", "Limit on days", "Limit on gear"], a: "Limit on weight of fish caught" },
    { q: "Individual Transferable Quota (ITQ) is?", opts: ["Right to catch share of TAC", "License to sail", "Tax", "Subsidy"], a: "Right to catch share of TAC" },
    { q: "Marine Protected Area (MPA) core zone?", opts: ["No-take zone", "Fishing allowed", "Tourism only", "Research only"], a: "No-take zone" },
    { q: "Buffer zone in MPA?", opts: ["Regulated activities allowed", "No entry", "Dynamite allowed", "Commercial fishing"], a: "Regulated activities allowed" },
    { q: "F-Factor in Fisheries Code refers to?", opts: ["Fishing effort limit", "Fuel factor", "Fish factor", "Funding"], a: "Fishing effort limit" },

    // --- FISH IDENTIFICATION (COMMERCIAL) ---
    { q: "Scientific name: Indian Mackerel?", opts: ["Rastrelliger kanagurta", "R. brachysoma", "R. faughni", "Decapterus"], a: "Rastrelliger kanagurta" },
    { q: "Scientific name: Short Mackerel (Hasa-hasa)?", opts: ["Rastrelliger brachysoma", "R. kanagurta", "Scomber", "Auxis"], a: "Rastrelliger brachysoma" },
    { q: "Scientific name: Frigate Tuna (Tulingan)?", opts: ["Auxis thazard", "Auxis rochei", "Katsuwonus", "Thunnus"], a: "Auxis thazard" },
    { q: "Scientific name: Bullet Tuna?", opts: ["Auxis rochei", "Auxis thazard", "Sarda", "Euthynnus"], a: "Auxis rochei" },
    { q: "Scientific name: Spanish Mackerel (Tanigue)?", opts: ["Scomberomorus commerson", "Sphyraena", "Acanthocybium", "Trichiurus"], a: "Scomberomorus commerson" },
    { q: "Scientific name: Bigeye Scad (Matangbaka)?", opts: ["Selar crumenophthalmus", "Decapterus", "Atule", "Caranx"], a: "Selar crumenophthalmus" },
    { q: "Scientific name: Slipmouth (Sapsap)?", opts: ["Leiognathus / Nuchequula", "Gazza", "Stolephorus", "Sardinella"], a: "Leiognathus / Nuchequula" },
    { q: "Scientific name: Anchovy (Dilis)?", opts: ["Stolephorus", "Sardinella", "Encrasicholina", "Engraulis"], a: "Stolephorus" },
    { q: "Scientific name: Threadfin Bream (Bisugo)?", opts: ["Nemipterus", "Lutjanus", "Caesio", "Upeneus"], a: "Nemipterus" },
    { q: "Scientific name: Grouper (Lapu-lapu)?", opts: ["Epinephelus / Plectropomus", "Lutjanus", "Lates", "Siganus"], a: "Epinephelus / Plectropomus" },
    { q: "Scientific name: Snapper (Maya-maya)?", opts: ["Lutjanus", "Lethrinus", "Caesio", "Pterocaesio"], a: "Lutjanus" },
    { q: "Scientific name: Rabbitfish (Danggit)?", opts: ["Siganus", "Scatophagus", "Acanthurus", "Naso"], a: "Siganus" },
    { q: "Scientific name: Squid (Pusit)?", opts: ["Loligo / Uroteuthis", "Sepia", "Octopus", "Nautilus"], a: "Loligo / Uroteuthis" },
    { q: "Scientific name: Blue Crab (Alimasag)?", opts: ["Portunus pelagicus", "Scylla serrata", "Charybdis", "Metapenaeus"], a: "Portunus pelagicus" },
    { q: "Fish with a suction cup on head?", opts: ["Remora (Echeneis)", "Goby", "Blenny", "Clingfish"], a: "Remora (Echeneis)" },
    { q: "Fish famous for puffer poison (Tetrodotoxin)?", opts: ["Tetraodontidae (Puffer)", "Diodon", "Ostracion", "Balistidae"], a: "Tetraodontidae (Puffer)" },
    { q: "Largest fish in the world?", opts: ["Whale Shark (Rhincodon typus)", "Blue Whale", "Great White", "Sunfish"], a: "Whale Shark (Rhincodon typus)" },
    { q: "Whale shark locally called?", opts: ["Butanding", "Dugong", "Pating", "Lumba-lumba"], a: "Butanding" },
    { q: "Dolphin locally called?", opts: ["Lumba-lumba", "Dugong", "Butanding", "Balyena"], a: "Lumba-lumba" },
    { q: "Sea cow locally called?", opts: ["Dugong", "Manatee", "Seal", "Walrus"], a: "Dugong" },
    { q: "Only herbivorous marine mammal?", opts: ["Dugong", "Dolphin", "Whale", "Seal"], a: "Dugong" },

    // --- LAWS (PENALTIES & AGENCIES) ---
    { q: "Penalty for Dynamite Fishing (RA 10654)?", opts: ["Admin Fine + Imprisonment", "Fine only", "Community service", "Warning"], a: "Admin Fine + Imprisonment" },
    { q: "Penalty for use of active gear in municipal waters?", opts: ["Fine + Confiscation", "Warning", "None", "Tax"], a: "Fine + Confiscation" },
    { q: "Agency managing Palawan fisheries?", opts: ["PCSD (Palawan Council for Sustainable Dev)", "BFAR Region 4B", "DENR", "LGU"], a: "PCSD (Palawan Council for Sustainable Dev)" },
    { q: "Agency for Laguna de Bay?", opts: ["LLDA", "BFAR 4A", "MMDA", "DENR"], a: "LLDA" },
    { q: "BFAR National Director is appointed by?", opts: ["President", "DA Secretary", "Senate", "Congress"], a: "President" },
    { q: "NFARMC stands for?", opts: ["National Fisheries and Aquatic Resources Management Council", "National Fish Association", "National Farm Council", "New Fisheries Act"], a: "National Fisheries and Aquatic Resources Management Council" },
    { q: "Composition of MFARMC?", opts: ["Fisherfolk, LGU, NGOs, Youth", "Politicians only", "Scientists only", "Military"], a: "Fisherfolk, LGU, NGOs, Youth" },
    { q: "Function of FARMC?", opts: ["Advisory / Recommendatory", "Law enforcement", "Judicial", "Executive"], a: "Advisory / Recommendatory" },
    { q: "Code of Conduct for Responsible Fisheries is by?", opts: ["FAO (UN)", "SEAFDEC", "ASEAN", "WHO"], a: "FAO (UN)" },
    { q: "UNCLOS stands for?", opts: ["United Nations Convention on the Law of the Sea", "United Nations Code for Law of Sea", "Union of National Coastal Laws", "Universal Code"], a: "United Nations Convention on the Law of the Sea" }
];
