// ecology.js
// Part 3 of 4: Ecology & Resources Board Exam Review Questions
// Topics: Limnology, Oceanography, Marine Ecosystems, Environmental Science

const ecologyQuestions = [
    // --- LIMNOLOGY (FRESHWATER ECOLOGY) ---
    { q: "Study of inland waters (lakes, rivers)?", opts: ["Limnology", "Oceanography", "Hydrology", "Potamology"], a: "Limnology" },
    { q: "Ecosystem with running water (River)?", opts: ["Lotic", "Lentic", "Pelagic", "Neritic"], a: "Lotic" },
    { q: "Ecosystem with standing water (Lake/Pond)?", opts: ["Lentic", "Lotic", "Estuarine", "Marine"], a: "Lentic" },
    { q: "Upper warm layer of a stratified lake?", opts: ["Epilimnion", "Hypolimnion", "Metalimnion", "Thermocline"], a: "Epilimnion" },
    { q: "Bottom cold layer of a stratified lake?", opts: ["Hypolimnion", "Epilimnion", "Metalimnion", "Benthos"], a: "Hypolimnion" },
    { q: "Middle layer with rapid temp change?", opts: ["Metalimnion / Thermocline", "Epilimnion", "Hypolimnion", "Surface"], a: "Metalimnion / Thermocline" },
    { q: "Lake rich in nutrients/productivity?", opts: ["Eutrophic", "Oligotrophic", "Mesotrophic", "Dystrophic"], a: "Eutrophic" },
    { q: "Lake with very low nutrients/clear water?", opts: ["Oligotrophic", "Eutrophic", "Mesotrophic", "Hypertrophic"], a: "Oligotrophic" },
    { q: "Brown-colored lake (humic acids)?", opts: ["Dystrophic", "Eutrophic", "Oligotrophic", "Clear"], a: "Dystrophic" },
    { q: "Process of nutrient enrichment leading to bloom?", opts: ["Eutrophication", "Stratification", "Sedimentation", "Nitrification"], a: "Eutrophication" },
    { q: "Maximum density of water is at?", opts: ["4°C", "0°C", "100°C", "25°C"], a: "4°C" },
    { q: "Deepest lake in the Philippines?", opts: ["Lake Mainit", "Laguna de Bay", "Taal Lake", "Lake Lanao"], a: "Lake Mainit" },
    { q: "Largest lake in the Philippines?", opts: ["Laguna de Bay", "Lake Lanao", "Taal Lake", "Naujan Lake"], a: "Laguna de Bay" },
    { q: "Endemic sardine in Taal Lake?", opts: ["Sardinella tawilis", "Sardinella lemuru", "Chanos chanos", "Mistichthys luzonensis"], a: "Sardinella tawilis" },
    { q: "Smallest commercial fish (Sinarapan) found in?", opts: ["Lake Buhi", "Lake Bato", "Taal Lake", "Laguna Lake"], a: "Lake Buhi" },
    { q: "River connecting Laguna de Bay to Manila Bay?", opts: ["Pasig River", "Marikina River", "Pampanga River", "Bicol River"], a: "Pasig River" },
    { q: "Zone of lake where light penetrates?", opts: ["Photic / Euphotic", "Aphotic", "Profundal", "Benthic"], a: "Photic / Euphotic" },
    { q: "Open water zone of a lake?", opts: ["Limnetic", "Littoral", "Benthic", "Profundal"], a: "Limnetic" },
    { q: "Shallow edge zone with rooted plants?", opts: ["Littoral", "Limnetic", "Pelagic", "Abyssal"], a: "Littoral" },
    { q: "Measure of water transparency?", opts: ["Secchi Disk", "Thermometer", "Barometer", "Anemometer"], a: "Secchi Disk" },
    { q: "Organism at the base of aquatic food web?", opts: ["Phytoplankton", "Zooplankton", "Fish", "Bacteria"], a: "Phytoplankton" },
    { q: "Primary productivity is measured in?", opts: ["g Carbon/m2/day", "kg/ha", "ppm", "psi"], a: "g Carbon/m2/day" },
    { q: "Method to measure primary productivity?", opts: ["Light and Dark Bottle", "Secchi Disk", "Imhoff Cone", "Titration"], a: "Light and Dark Bottle" },
    { q: "Dark bottle measures?", opts: ["Respiration", "Photosynthesis", "Gross Production", "Net Production"], a: "Respiration" },
    { q: "Light bottle measures?", opts: ["Net Production + Respiration", "Respiration only", "Decomposition", "Nothing"], a: "Net Production + Respiration" },

    // --- OCEANOGRAPHY (PHYSICAL & CHEMICAL) ---
    { q: "Average salinity of the ocean?", opts: ["35 ppt", "25 ppt", "15 ppt", "50 ppt"], a: "35 ppt" },
    { q: "Most abundant salt in seawater?", opts: ["Sodium Chloride (NaCl)", "Magnesium Chloride", "Calcium Carbonate", "Potassium"], a: "Sodium Chloride (NaCl)" },
    { q: "Zone where river meets the sea?", opts: ["Estuary", "Delta", "Lagoon", "Strait"], a: "Estuary" },
    { q: "Sharp change in salinity?", opts: ["Halocline", "Thermocline", "Pycnocline", "Chemocline"], a: "Halocline" },
    { q: "Sharp change in density?", opts: ["Pycnocline", "Thermocline", "Halocline", "Barocline"], a: "Pycnocline" },
    { q: "Deepest part of the ocean?", opts: ["Marianas Trench", "Philippine Trench", "Tonga Trench", "Puerto Rico Trench"], a: "Marianas Trench" },
    { q: "Depth of the Marianas Trench?", opts: ["~11,000 meters", "8,000 meters", "5,000 meters", "20,000 meters"], a: "~11,000 meters" },
    { q: "Deepest point in the Philippines?", opts: ["Philippine Trench (Emden Deep)", "Sulu Sea", "Manila Trench", "Celebes Sea"], a: "Philippine Trench (Emden Deep)" },
    { q: "Phenomenon of warming Pacific Ocean?", opts: ["El Nino", "La Nina", "Monsoon", "Typhoon"], a: "El Nino" },
    { q: "Phenomenon of cooling Pacific Ocean?", opts: ["La Nina", "El Nino", "Global Warming", "Greenhouse Effect"], a: "La Nina" },
    { q: "Effect of El Nino in Philippines?", opts: ["Drought / Less Rain", "Floods", "Typhoons", "Snow"], a: "Drought / Less Rain" },
    { q: "Effect of La Nina in Philippines?", opts: ["Heavy Rainfall / Floods", "Drought", "Heatwave", "Dry spell"], a: "Heavy Rainfall / Floods" },
    { q: "Coriolis effect deflects currents in N. Hemisphere to?", opts: ["Right", "Left", "Up", "Down"], a: "Right" },
    { q: "Major current passing East of Philippines?", opts: ["North Equatorial Current", "Kuroshio", "Gulf Stream", "Humboldt"], a: "North Equatorial Current" },
    { q: "Upwelling brings?", opts: ["Nutrients to surface", "Warm water down", "Oxygen down", "Fish away"], a: "Nutrients to surface" },
    { q: "Tide with one high and one low per day?", opts: ["Diurnal", "Semi-diurnal", "Mixed", "Solar"], a: "Diurnal" },
    { q: "Tide with two equal highs and lows?", opts: ["Semi-diurnal", "Diurnal", "Mixed", "Lunar"], a: "Semi-diurnal" },
    { q: "Tide typical in the Philippines?", opts: ["Mixed Diurnal", "Pure Diurnal", "Pure Semi-diurnal", "None"], a: "Mixed Diurnal" },
    { q: "Highest high tide (New/Full Moon)?", opts: ["Spring Tide", "Neap Tide", "Red Tide", "Low Tide"], a: "Spring Tide" },
    { q: "Lowest high tide (Quarter Moons)?", opts: ["Neap Tide", "Spring Tide", "Rip Tide", "Ebb Tide"], a: "Neap Tide" },
    { q: "Tsunami is caused by?", opts: ["Earthquake / Undersea displacement", "Wind", "Tide", "Storm"], a: "Earthquake / Undersea displacement" },
    { q: "Storm surge is caused by?", opts: ["Low pressure / Wind (Typhoon)", "Earthquake", "Tide", "Moon"], a: "Low pressure / Wind (Typhoon)" },
    { q: "Philippine Rise is formerly?", opts: ["Benham Rise", "Scarborough", "Spratly", "Recto"], a: "Benham Rise" },
    { q: "West Philippine Sea includes?", opts: ["Scarborough Shoal / Spratlys", "Benham Rise", "Sulu Sea", "Celebes Sea"], a: "Scarborough Shoal / Spratlys" },
    { q: "Archipelagic Doctrine principle?", opts: ["Waters between islands are internal", "Islands are separate", "Open sea is free", "EEZ is 12 miles"], a: "Waters between islands are internal" },

    // --- MARINE ECOSYSTEMS (CORAL, MANGROVE, SEAGRASS) ---
    { q: "Mangrove aerial roots are called?", opts: ["Pneumatophores", "Prop roots", "Buttress", "Stilt"], a: "Pneumatophores" },
    { q: "Scientific name of 'Bakawan' (Prop roots)?", opts: ["Rhizophora", "Avicennia", "Sonneratia", "Nypa"], a: "Rhizophora" },
    { q: "Scientific name of 'Api-api' (Pencil roots)?", opts: ["Avicennia", "Rhizophora", "Bruguiera", "Ceriops"], a: "Avicennia" },
    { q: "Scientific name of 'Pagatpat'?", opts: ["Sonneratia alba", "Avicennia", "Rhizophora", "Nypa"], a: "Sonneratia alba" },
    { q: "Scientific name of Nipa Palm?", opts: ["Nypa fruticans", "Cocos nucifera", "Areca catechu", "Corypha"], a: "Nypa fruticans" },
    { q: "Ecological function of mangroves?", opts: ["Nursery / Coast protection", "Coral bleaching", "Oxygen depletion", "Sand mining"], a: "Nursery / Coast protection" },
    { q: "Seagrass vs Seaweed: Seagrass has?", opts: ["True roots, flowers, veins", "Holdfast only", "Spores", "No veins"], a: "True roots, flowers, veins" },
    { q: "Scientific name of Dugong Grass?", opts: ["Thalassia hemprichii", "Enhalus acoroides", "Halophila", "Cymodocea"], a: "Thalassia hemprichii" },
    { q: "Largest seagrass species in PH?", opts: ["Enhalus acoroides", "Thalassia", "Halodule", "Syringodium"], a: "Enhalus acoroides" },
    { q: "Coral Reefs are built by?", opts: ["Coral Polyps + Zooxanthellae", "Algae only", "Fish", "Rocks"], a: "Coral Polyps + Zooxanthellae" },
    { q: "Symbiotic algae in corals?", opts: ["Zooxanthellae", "Spirulina", "Chlorella", "Sargassum"], a: "Zooxanthellae" },
    { q: "Coral bleaching is caused by?", opts: ["High temperature / Stress", "Overfishing", "Dynamite", "Cold"], a: "High temperature / Stress" },
    { q: "Coral reefs grow best in?", opts: ["Clear, warm, oligotrophic water", "Turbid water", "Cold water", "Rich nutrient water"], a: "Clear, warm, oligotrophic water" },
    { q: "Crown of Thorns Starfish eats?", opts: ["Coral polyps", "Algae", "Fish", "Sand"], a: "Coral polyps" },
    { q: "Scientific name of Crown of Thorns?", opts: ["Acanthaster planci", "Linckia", "Protoreaster", "Culcita"], a: "Acanthaster planci" },
    { q: "Most diverse marine ecosystem?", opts: ["Coral Reef", "Mangrove", "Seagrass", "Estuary"], a: "Coral Reef" },
    { q: "Fish indicator of healthy reef?", opts: ["Chaetodontidae (Butterflyfish)", "Tilapia", "Bangus", "Catfish"], a: "Chaetodontidae (Butterflyfish)" },
    { q: "Marine protected area (MPA) benefit?", opts: ["Spillover effect", "Tourism only", "Less fish", "Restriction only"], a: "Spillover effect" },
    { q: "Blue Carbon refers to?", opts: ["Carbon stored in marine ecosystems", "Atmospheric carbon", "Coal", "Oil"], a: "Carbon stored in marine ecosystems" },
    { q: "Major Blue Carbon sinks?", opts: ["Mangroves / Seagrass / Saltmarsh", "Coral reefs", "Open ocean", "Beaches"], a: "Mangroves / Seagrass / Saltmarsh" },

    // --- ENVIRONMENTAL ISSUES ---
    { q: "Red Tide is caused by?", opts: ["Dinoflagellates", "Diatoms", "Blue-green algae", "Bacteria"], a: "Dinoflagellates" },
    { q: "Paralytic Shellfish Poisoning (PSP) agent?", opts: ["Pyrodinium bahamense", "Skeletonema", "Chaetoceros", "Sargassum"], a: "Pyrodinium bahamense" },
    { q: "Toxin causing PSP?", opts: ["Saxitoxin", "Tetrodotoxin", "Ciguatoxin", "Aflatoxin"], a: "Saxitoxin" },
    { q: "Ciguatera poisoning comes from?", opts: ["Reef fish (Barracuda/Grouper)", "Shellfish", "Sardines", "Tuna"], a: "Reef fish (Barracuda/Grouper)" },
    { q: "Ciguatera toxin source?", opts: ["Gambierdiscus toxicus", "Pyrodinium", "Gymnodinium", "Vibrio"], a: "Gambierdiscus toxicus" },
    { q: "Amnesic Shellfish Poisoning caused by?", opts: ["Pseudo-nitzschia (Diatom)", "Pyrodinium", "Alexandrium", "Dinophysis"], a: "Pseudo-nitzschia (Diatom)" },
    { q: "Diarrhetic Shellfish Poisoning caused by?", opts: ["Dinophysis", "Pyrodinium", "Nitzschia", "Gymnodinium"], a: "Dinophysis" },
    { q: "Neurotoxic Shellfish Poisoning caused by?", opts: ["Karenia brevis / Gymnodinium", "Pyrodinium", "Vibrio", "E. coli"], a: "Karenia brevis / Gymnodinium" },
    { q: "Fish Kill causes?", opts: ["Depletion of DO / Ammonia spike", "Overfeeding", "Heavy rain", "All of the above"], a: "All of the above" },
    { q: "Greenhouse effect is caused by?", opts: ["CO2, Methane, Water vapor", "Oxygen", "Nitrogen", "Argon"], a: "CO2, Methane, Water vapor" },
    { q: "Main cause of Ocean Acidification?", opts: ["Absorption of excess CO2", "Acid rain", "Pollution", "Sewage"], a: "Absorption of excess CO2" },
    { q: "Ocean Acidification affects?", opts: ["Calcifying organisms (Corals/Shells)", "Fish swimming", "Algae growth", "Currents"], a: "Calcifying organisms (Corals/Shells)" },
    { q: "Minamata disease caused by?", opts: ["Mercury", "Lead", "Cadmium", "Arsenic"], a: "Mercury" },
    { q: "Itai-itai disease caused by?", opts: ["Cadmium", "Mercury", "Lead", "Copper"], a: "Cadmium" },
    { q: "Biomagnification means?", opts: ["Toxin concentration increases up food chain", "Bioaccumulation", "Dilution", "Excretion"], a: "Toxin concentration increases up food chain" },
    { q: "Oil spill dispersants work by?", opts: ["Breaking oil into droplets", "Sinking oil", "Evaporating oil", "Burning oil"], a: "Breaking oil into droplets" },
    { q: "Coliform bacteria indicate?", opts: ["Fecal contamination", "Chemical pollution", "Oil spill", "Heavy metals"], a: "Fecal contamination" },
    { q: "Great Pacific Garbage Patch is mostly?", opts: ["Microplastics", "Glass", "Metal", "Paper"], a: "Microplastics" },
    { q: "Biodiversity refers to?", opts: ["Variety of life", "Number of animals", "Forest area", "Coral cover"], a: "Variety of life" },
    { q: "Convention on International Trade in Endangered Species?", opts: ["CITES", "UNCLOS", "CBD", "RAMSAR"], a: "CITES" },
    { q: "Ramsar Convention protects?", opts: ["Wetlands", "Forests", "Corals", "Mountains"], a: "Wetlands" },
    { q: "Kyoto Protocol addresses?", opts: ["Greenhouse gas emissions", "Ozone layer", "Biodiversity", "Ocean pollution"], a: "Greenhouse gas emissions" },
    { q: "Montreal Protocol addresses?", opts: ["Ozone depleting substances", "Climate change", "Marine debris", "Nuclear waste"], a: "Ozone depleting substances" },
  // --- BATCH 2: QUESTIONS 101-200 ---
    // --- ADVANCED LIMNOLOGY ---
    { q: "Lake mixing once a year?", opts: ["Monomictic", "Dimictic", "Polymictic", "Amictic"], a: "Monomictic" },
    { q: "Lake mixing twice a year?", opts: ["Dimictic", "Monomictic", "Oligomictic", "Meromictic"], a: "Dimictic" },
    { q: "Lake that never mixes (permanently stratified)?", opts: ["Meromictic", "Holomictic", "Dimictic", "Polymictic"], a: "Meromictic" },
    { q: "Deepest layer of non-mixing water in a meromictic lake?", opts: ["Monimolimnion", "Mixolimnion", "Epilimnion", "Metalimnion"], a: "Monimolimnion" },
    { q: "Lake mixing frequently (tropical shallow lakes)?", opts: ["Polymictic", "Dimictic", "Amictic", "Cold Monomictic"], a: "Polymictic" },
    { q: "Classification of Philippine lakes generally?", opts: ["Warm Monomictic / Polymictic", "Dimictic", "Cold Monomictic", "Amictic"], a: "Warm Monomictic / Polymictic" },
    { q: "Standing wave in a lake (sloshing)?", opts: ["Seiche", "Tide", "Current", "Tsunami"], a: "Seiche" },
    { q: "Circular water motion caused by wind?", opts: ["Langmuir Circulation", "Ekman Spiral", "Upwelling", "Downwelling"], a: "Langmuir Circulation" },
    { q: "Organisms swimming against current?", opts: ["Nekton", "Plankton", "Neuston", "Benthos"], a: "Nekton" },
    { q: "Organisms drifting with current?", opts: ["Plankton", "Nekton", "Benthos", "Periphyton"], a: "Plankton" },
    { q: "Organisms living on the surface film?", opts: ["Neuston", "Pleuston", "Plankton", "Nekton"], a: "Neuston" },
    { q: "Organisms attached to submerged surfaces?", opts: ["Periphyton / Aufwuchs", "Phytoplankton", "Zooplankton", "Nekton"], a: "Periphyton / Aufwuchs" },
    { q: "Organisms living at the bottom?", opts: ["Benthos", "Nekton", "Plankton", "Neuston"], a: "Benthos" },
    { q: "Benthos living inside the sediment?", opts: ["Infauna", "Epifauna", "Demersal", "Pelagic"], a: "Infauna" },
    { q: "Benthos living on top of the sediment?", opts: ["Epifauna", "Infauna", "Burrowers", "Borers"], a: "Epifauna" },
    { q: "Decomposition of organic matter requires?", opts: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"], a: "Oxygen" },
    { q: "Ratio of Photosynthesis to Respiration (P/R) in eutrophic lakes?", opts: ["> 1", "< 1", "Equal to 1", "Zero"], a: "> 1" },
    { q: "External source of nutrients (runoff)?", opts: ["Allochthonous", "Autochthonous", "Atmospheric", "Sedimentary"], a: "Allochthonous" },
    { q: "Internal source of nutrients (cycling)?", opts: ["Autochthonous", "Allochthonous", "Inflow", "Rain"], a: "Autochthonous" },
    { q: "Measure of light extinction in water?", opts: ["Extinction Coefficient (k)", "Refraction Index", "Salinity", "Density"], a: "Extinction Coefficient (k)" },

    // --- BIOLOGICAL OCEANOGRAPHY (PLANKTON) ---
    { q: "Plankton that spend whole life as plankton?", opts: ["Holoplankton", "Meroplankton", "Nanoplankton", "Picoplankton"], a: "Holoplankton" },
    { q: "Plankton that are only temporary (larvae)?", opts: ["Meroplankton", "Holoplankton", "Megaplankton", "Macroplankton"], a: "Meroplankton" },
    { q: "Example of Holoplankton?", opts: ["Copepods / Diatoms", "Crab larvae", "Fish eggs", "Shrimp nauplius"], a: "Copepods / Diatoms" },
    { q: "Example of Meroplankton?", opts: ["Fish larvae / Veliger", "Chaetoceros", "Rotifer", "Krill"], a: "Fish larvae / Veliger" },
    { q: "Size class: 2 - 20 microns?", opts: ["Nanoplankton", "Microplankton", "Picoplankton", "Mesoplankton"], a: "Nanoplankton" },
    { q: "Size class: 0.2 - 2 microns?", opts: ["Picoplankton", "Nanoplankton", "Femtoplanlton", "Microplankton"], a: "Picoplankton" },
    { q: "Size class: 20 - 200 microns (standard net)?", opts: ["Microplankton", "Mesoplankton", "Macroplankton", "Megaplankton"], a: "Microplankton" },
    { q: "Deep scattering layer is caused by?", opts: ["Vertical migration of zooplankton/fish", "Sediments", "Pollution", "Whales"], a: "Vertical migration of zooplankton/fish" },
    { q: "Diel Vertical Migration: Zooplankton go up at?", opts: ["Night", "Day", "Noon", "Midnight"], a: "Night" },
    { q: "Reason for Diel Vertical Migration?", opts: ["Avoid predators / Feed", "Reproduction", "Temperature", "Currents"], a: "Avoid predators / Feed" },
    { q: "Major nutrient limiting in the Ocean?", opts: ["Nitrogen", "Phosphorus", "Silicon", "Iron"], a: "Nitrogen" },
    { q: "Iron limitation is common in?", opts: ["HNLC zones (High Nutrient Low Chlorophyll)", "Estuaries", "Coral reefs", "Upwelling areas"], a: "HNLC zones (High Nutrient Low Chlorophyll)" },
    { q: "Redfield Ratio (C:N:P)?", opts: ["106:16:1", "1:1:1", "50:10:1", "100:10:1"], a: "106:16:1" },
    { q: "Compensation depth is where?", opts: ["Photosynthesis = Respiration", "No light exists", "Max photosynthesis", "Surface"], a: "Photosynthesis = Respiration" },
    { q: "Critical depth is where?", opts: ["Total Plant Production = Total Plant Respiration", "P > R", "P < R", "Surface"], a: "Total Plant Production = Total Plant Respiration" },
    { q: "Dinoflagellate capability?", opts: ["Bioluminescence / Mobility", "Silica shell", "Fix nitrogen", "Multicellular"], a: "Bioluminescence / Mobility" },
    { q: "Diatom shell is made of?", opts: ["Silica (SiO2)", "Calcium Carbonate", "Cellulose", "Chitin"], a: "Silica (SiO2)" },
    { q: "Coccolithophore shell is made of?", opts: ["Calcium Carbonate", "Silica", "Cellulose", "Iron"], a: "Calcium Carbonate" },
    { q: "Primary production in the ocean is highest in?", opts: ["Upwelling zones / Coastal areas", "Open ocean (Gyres)", "Deep sea", "Trenches"], a: "Upwelling zones / Coastal areas" },
    { q: "Ocean deserts (low productivity) are found in?", opts: ["Subtropical Gyres", "Equator", "Poles", "Coasts"], a: "Subtropical Gyres" },

    // --- PHYSICAL OCEANOGRAPHY & CLIMATE ---
    { q: "Ekman transport is?", opts: ["Net water movement 90 deg to wind", "Parallel to wind", "Opposite to wind", "Vertical"], a: "Net water movement 90 deg to wind" },
    { q: "Thermohaline circulation is driven by?", opts: ["Density (Temp + Salinity)", "Wind", "Tides", "Moon"], a: "Density (Temp + Salinity)" },
    { q: "Global Conveyor Belt refers to?", opts: ["Deep ocean circulation", "Surface currents", "Wind patterns", "Trade winds"], a: "Deep ocean circulation" },
    { q: "ENSO stands for?", opts: ["El Nino Southern Oscillation", "El Nino Summer Oscillation", "East North South Ocean", "Equatorial Northern Southern Oscillation"], a: "El Nino Southern Oscillation" },
    { q: "During El Nino, trade winds?", opts: ["Weaken", "Strengthen", "Reverse West", "Stop"], a: "Weaken" },
    { q: "During La Nina, trade winds?", opts: ["Strengthen", "Weaken", "Stop", "Reverse"], a: "Strengthen" },
    { q: "Current moving warm water from Philippines to Japan?", opts: ["Kuroshio Current", "Oyashio Current", "California Current", "Humboldt Current"], a: "Kuroshio Current" },
    { q: "Cold current meeting Kuroshio?", opts: ["Oyashio Current", "Gulf Stream", "Canary Current", "Benguela Current"], a: "Oyashio Current" },
    { q: "Pacific Ring of Fire is known for?", opts: ["Volcanoes / Earthquakes", "Hurricanes", "Droughts", "Floods"], a: "Volcanoes / Earthquakes" },
    { q: "Fetch is?", opts: ["Distance wind blows over water", "Wave height", "Wave period", "Tide height"], a: "Distance wind blows over water" },
    { q: "Wave height depends on?", opts: ["Wind speed, Duration, Fetch", "Temperature", "Salinity", "Depth only"], a: "Wind speed, Duration, Fetch" },
    { q: "Swell refers to?", opts: ["Waves generated by distant storms", "Wind waves", "Tides", "Tsunamis"], a: "Waves generated by distant storms" },
    { q: "Spring tides occur during?", opts: ["New Moon and Full Moon", "Quarter Moons", "Daytime", "Nighttime"], a: "New Moon and Full Moon" },
    { q: "Neap tides occur during?", opts: ["1st and 3rd Quarter Moons", "New Moon", "Full Moon", "Summer"], a: "1st and 3rd Quarter Moons" },
    { q: "Zone between high and low tide?", opts: ["Intertidal / Littoral", "Subtidal", "Supratidal", "Pelagic"], a: "Intertidal / Littoral" },
    { q: "Splash zone (above high tide)?", opts: ["Supratidal", "Intertidal", "Subtidal", "Neritic"], a: "Supratidal" },
    { q: "Subtidal zone is?", opts: ["Always submerged", "Exposed at low tide", "Splash zone", "Deep sea"], a: "Always submerged" },
    { q: "Oxygen Minimum Zone (OMZ) is usually at?", opts: ["200 - 1000m depth", "Surface", "Bottom", "10m"], a: "200 - 1000m depth" },
    { q: "Why is Oxygen low in OMZ?", opts: ["Bacterial respiration / Decomposition", "Photosynthesis", "Mixing", "High pressure"], a: "Bacterial respiration / Decomposition" },
    { q: "Gas soluble in seawater increases with?", opts: ["Decreasing Temp / Pressure", "Increasing Temp", "High Salinity", "Low Pressure"], a: "Decreasing Temp / Pressure" },

    // --- ECOTOXICOLOGY & POLLUTION ---
    { q: "BOD stands for?", opts: ["Biological Oxygen Demand", "Basic Oxygen Demand", "Bacterial Oxygen Demand", "Bio-Organic Decay"], a: "Biological Oxygen Demand" },
    { q: "COD stands for?", opts: ["Chemical Oxygen Demand", "Carbon Oxygen Demand", "Clean Ocean Drive", "Critical Oxygen Depth"], a: "Chemical Oxygen Demand" },
    { q: "COD is usually?", opts: ["Higher than BOD", "Lower than BOD", "Equal to BOD", "Zero"], a: "Higher than BOD" },
    { q: "LC50 stands for?", opts: ["Lethal Concentration 50%", "Low Concentration", "Live Count", "Level of Carbon"], a: "Lethal Concentration 50%" },
    { q: "Bioaccumulation is?", opts: ["Accumulation in single organism over time", "Food chain transfer", "Excretion", "Breakdown"], a: "Accumulation in single organism over time" },
    { q: "Biomagnification is?", opts: ["Increase in concentration up the food chain", "Single organism", "Dilution", "Filtration"], a: "Increase in concentration up the food chain" },
    { q: "Eutrophication is caused by excess?", opts: ["Nitrogen and Phosphorus", "Carbon", "Oxygen", "Iron"], a: "Nitrogen and Phosphorus" },
    { q: "Hypoxia is defined as DO below?", opts: ["2-3 mg/L", "5 mg/L", "10 mg/L", "0 mg/L"], a: "2-3 mg/L" },
    { q: "Anoxia is defined as DO?", opts: ["0 mg/L (None)", "2 mg/L", "5 mg/L", "10 mg/L"], a: "0 mg/L (None)" },
    { q: "Heavy metal causing Minamata?", opts: ["Mercury (Methylmercury)", "Lead", "Cadmium", "Copper"], a: "Mercury (Methylmercury)" },
    { q: "Heavy metal causing Itai-itai?", opts: ["Cadmium", "Mercury", "Lead", "Arsenic"], a: "Cadmium" },
    { q: "Source of thermal pollution?", opts: ["Power plants", "Sewage", "Agriculture", "Mining"], a: "Power plants" },
    { q: "Main effect of thermal pollution?", opts: ["Lowers DO / Alters metabolism", "Increases DO", "Kills bacteria", "Cleans water"], a: "Lowers DO / Alters metabolism" },
    { q: "Microplastics size?", opts: ["< 5mm", "> 5mm", "1 meter", "Invisible"], a: "< 5mm" },
    { q: "Ghost nets are?", opts: ["Abandoned fishing gear", "Spider webs", "Plankton nets", "Safety nets"], a: "Abandoned fishing gear" },
    { q: "Oil spill cleanup using bacteria?", opts: ["Bioremediation", "Chemical dispersant", "Skimming", "Burning"], a: "Bioremediation" },
    { q: "Indicator organism for fecal pollution?", opts: ["E. coli / Coliforms", "Vibrio", "Salmonella", "Algae"], a: "E. coli / Coliforms" },
    { q: "EIA stands for?", opts: ["Environmental Impact Assessment", "Ecological Index Area", "Energy Impact Analysis", "Earth Institute Agency"], a: "Environmental Impact Assessment" },
    { q: "ECC stands for?", opts: ["Environmental Compliance Certificate", "Energy Conservation Code", "Earth Care Center", "Eco City Council"], a: "Environmental Compliance Certificate" },
    { q: "Key law for Solid Waste Management?", opts: ["RA 9003", "RA 8550", "RA 9275", "RA 8749"], a: "RA 9003" }
];
