// postharvest.js
// Part 4 of 4: Post-Harvest Fisheries Board Exam Review Questions
// Topics: Processing, Food Safety (HACCP), Chemistry, Microbiology

const postharvestQuestions = [
    // --- FISH MICROBIOLOGY & SPOILAGE ---
    { q: "Primary concern in canned low-acid foods?", opts: ["Clostridium botulinum", "Salmonella", "E. coli", "Vibrio"], a: "Clostridium botulinum" },
    { q: "Histamine poisoning is associated with?", opts: ["Scombridae (Tuna/Mackerel)", "Milkfish", "Tilapia", "Carp"], a: "Scombridae (Tuna/Mackerel)" },
    { q: "Histamine is formed from?", opts: ["Histidine", "Lysine", "Protein", "Fat"], a: "Histidine" },
    { q: "Chemical indicator of spoilage in marine fish?", opts: ["Trimethylamine (TMA)", "Ammonia", "Urea", "Lactic Acid"], a: "Trimethylamine (TMA)" },
    { q: "Bacteria that grow in cold temperatures?", opts: ["Psychrophiles", "Thermophiles", "Mesophiles", "Halophiles"], a: "Psychrophiles" },
    { q: "Bacteria that love salt?", opts: ["Halophiles", "Psychrophiles", "Acidophiles", "Thermophiles"], a: "Halophiles" },
    { q: "Pathogen common in raw oysters?", opts: ["Vibrio vulnificus", "Salmonella", "Staphylococcus", "Listeria"], a: "Vibrio vulnificus" },
    { q: "Stiffening of fish muscle after death?", opts: ["Rigor Mortis", "Autolysis", "Putrefaction", "Oxidation"], a: "Rigor Mortis" },
    { q: "Self-digestion of fish by enzymes?", opts: ["Autolysis", "Oxidation", "Rancidity", "Hydrolysis"], a: "Autolysis" },
    { q: "Odor of spoiled fish (TMA) smells like?", opts: ["Fishy / Ammonia-like", "Sweet", "Fruity", "Burnt"], a: "Fishy / Ammonia-like" },
    { q: "Bacterial count limit for fresh fish (Export)?", opts: ["500,000 cfu/g", "10 million cfu/g", "100 cfu/g", "Zero"], a: "500,000 cfu/g" },
    { q: "Source of Staphylococcus aureus in fish?", opts: ["Food handlers / Humans", "Sea water", "Soil", "Fish guts"], a: "Food handlers / Humans" },
    { q: "Salmonella is primarily found in?", opts: ["Intestine / Feces", "Skin", "Gills", "Muscle"], a: "Intestine / Feces" },
    { q: "Mold growing on dried fish?", opts: ["Aspergillus / Dun", "Penicillium", "Yeast", "Bacteria"], a: "Aspergillus / Dun" },
    { q: "Toxin produced by Aspergillus flavus?", opts: ["Aflatoxin", "Botulinum", "Tetrodotoxin", "Saxitoxin"], a: "Aflatoxin" },
    { q: "Pink/Red discoloration in salted fish?", opts: ["Halophilic bacteria (Halobacterium)", "Blood", "Dye", "Mold"], a: "Halophilic bacteria (Halobacterium)" },
    { q: "Phase of bacterial growth with rapid increase?", opts: ["Log / Exponential Phase", "Lag Phase", "Stationary Phase", "Death Phase"], a: "Log / Exponential Phase" },
    { q: "Water activity (Aw) limit for bacterial growth?", opts: ["0.90", "0.60", "0.50", "0.10"], a: "0.90" },
    { q: "Aw of pure water?", opts: ["1.0", "0.0", "0.5", "100"], a: "1.0" },
    { q: "pH where Clostridium botulinum stops growing?", opts: ["4.6", "7.0", "9.0", "10.0"], a: "4.6" },

    // --- HANDLING & CHILLING ---
    { q: "Temperature range for chilling fish?", opts: ["0°C to 4°C", "-18°C", "10°C", "25°C"], a: "0°C to 4°C" },
    { q: "Ratio of Ice to Fish (Tropical conditions)?", opts: ["1:1", "1:2", "1:5", "1:10"], a: "1:1" },
    { q: "Best ice for rapid cooling?", opts: ["Flake / Crushed ice", "Block ice", "Tube ice", "Dry ice"], a: "Flake / Crushed ice" },
    { q: "Chilling method using seawater + ice?", opts: ["CSW (Chilled Seawater)", "RSW", "Blast freezing", "Glazing"], a: "CSW (Chilled Seawater)" },
    { q: "Chilling method using mechanical refrigeration?", opts: ["RSW (Refrigerated Seawater)", "CSW", "Icing", "Drying"], a: "RSW (Refrigerated Seawater)" },
    { q: "Proper way to ice fish?", opts: ["Layers of ice and fish", "Ice on top only", "Ice at bottom only", "Fish on top"], a: "Layers of ice and fish" },
    { q: "Insulation material for fish boxes?", opts: ["Polyurethane / Styrofoam", "Wood", "Metal", "Plastic"], a: "Polyurethane / Styrofoam" },
    { q: "Removing internal organs is called?", opts: ["Evisceration / Gutting", "Filleting", "Scaling", "Skinning"], a: "Evisceration / Gutting" },
    { q: "Why eviscerate fish immediately?", opts: ["Remove enzymes/bacteria", "Make it lighter", "Better look", "Remove bones"], a: "Remove enzymes/bacteria" },
    { q: "Gaffing fish should be done in the?", opts: ["Head", "Body", "Tail", "Stomach"], a: "Head" },
    { q: "Bruising in fish is caused by?", opts: ["Rough handling", "Bacteria", "Ice", "Salt"], a: "Rough handling" },
    { q: "Burst belly is caused by?", opts: ["Digestive enzymes (Autolysis)", "Bacteria", "Freezing", "Cooking"], a: "Digestive enzymes (Autolysis)" },
    { q: "Green meat in Tuna is caused by?", opts: ["Oxidation", "H2S bacteria", "Histamine", "Bleeding"], a: "Oxidation" },
    { q: "Burnt Tuna (Yake) is caused by?", opts: ["High temperature / Stress at harvest", "Freezing", "Bacteria", "Salt"], a: "High temperature / Stress at harvest" },
    { q: "Process of bleeding tuna?", opts: ["Sashimi grade handling", "Canning", "Drying", "Salting"], a: "Sashimi grade handling" },

    // --- FREEZING & COLD STORAGE ---
    { q: "Standard temperature for frozen storage?", opts: ["-18°C or lower", "0°C", "-5°C", "-10°C"], a: "-18°C or lower" },
    { q: "Freezing method: Fast vs Slow?", opts: ["Fast freezing is better", "Slow freezing is better", "Same", "None"], a: "Fast freezing is better" },
    { q: "Why is fast freezing better?", opts: ["Small ice crystals formed", "Large crystals", "Kills bacteria", "Adds flavor"], a: "Small ice crystals formed" },
    { q: "Large ice crystals cause?", opts: ["Cell rupture / Drip loss", "Better texture", "Preservation", "Whitening"], a: "Cell rupture / Drip loss" },
    { q: "Zone of maximum crystal formation?", opts: ["-1°C to -5°C", "0°C to 4°C", "-20°C", "10°C"], a: "-1°C to -5°C" },
    { q: "Application of thin ice layer on frozen fish?", opts: ["Glazing", "Breading", "Salting", "Smoking"], a: "Glazing" },
    { q: "Purpose of Glazing?", opts: ["Prevent oxidation / Freezer burn", "Add weight", "Cook", "Thaw"], a: "Prevent oxidation / Freezer burn" },
    { q: "Freezer burn is caused by?", opts: ["Sublimation of water (Dehydration)", "Heat", "Bacteria", "Mold"], a: "Sublimation of water (Dehydration)" },
    { q: "Equipment for rapid freezing (Air)?", opts: ["Blast Freezer", "Plate Freezer", "Chest Freezer", "Refrigerator"], a: "Blast Freezer" },
    { q: "Equipment for freezing blocks (Contact)?", opts: ["Contact Plate Freezer", "Blast Freezer", "Tunnel Freezer", "Brine Freezer"], a: "Contact Plate Freezer" },
    { q: "Freezing using liquid nitrogen?", opts: ["Cryogenic Freezing", "Blast Freezing", "Sharp Freezing", "Still Air"], a: "Cryogenic Freezing" },
    { q: "IQF stands for?", opts: ["Individually Quick Frozen", "International Quality Fish", "Ice Quality Freeze", "Instant Quick Fish"], a: "Individually Quick Frozen" },
    { q: "Thawing is the reverse of?", opts: ["Freezing", "Drying", "Canning", "Smoking"], a: "Freezing" },
    { q: "Drip loss occurs during?", opts: ["Thawing", "Freezing", "Cooking", "Canning"], a: "Thawing" },
    { q: "Rancidity in frozen fish is due to?", opts: ["Lipid Oxidation", "Protein denaturation", "Bacteria", "Water"], a: "Lipid Oxidation" },

    // --- THERMAL PROCESSING (CANNING) ---
    { q: "Goal of canning?", opts: ["Commercial Sterility", "Pasteurization", "Drying", "Freezing"], a: "Commercial Sterility" },
    { q: "Equipment used for thermal processing?", opts: ["Retort / Autoclave", "Oven", "Freezer", "Smoker"], a: "Retort / Autoclave" },
    { q: "Standard temperature for retorting?", opts: ["116°C - 121°C (240-250°F)", "100°C", "80°C", "150°C"], a: "116°C - 121°C (240-250°F)" },
    { q: "Pressure corresponding to 121°C?", opts: ["15 psi", "10 psi", "0 psi", "50 psi"], a: "15 psi" },
    { q: "Target organism in canning (F0 value)?", opts: ["C. botulinum spores", "E. coli", "Salmonella", "Yeast"], a: "C. botulinum spores" },
    { q: "Cold point in a can (Conduction)?", opts: ["Geometric center", "Bottom", "Top", "Side"], a: "Geometric center" },
    { q: "Cold point in a can (Convection)?", opts: ["Below geometric center", "Center", "Top", "Side"], a: "Below geometric center" },
    { q: "Heating by Conduction is for?", opts: ["Solid packs (Tuna)", "Liquid packs", "Soups", "Water"], a: "Solid packs (Tuna)" },
    { q: "Heating by Convection is for?", opts: ["Liquids / Brine packs", "Solids", "Meats", "Paste"], a: "Liquids / Brine packs" },
    { q: "Removing air from the can before sealing?", opts: ["Exhausting", "Blanching", "Retorting", "Cooling"], a: "Exhausting" },
    { q: "Why exhaust cans?", opts: ["Create vacuum / Prevent buckling", "Add air", "Cook fish", "Kill bacteria"], a: "Create vacuum / Prevent buckling" },
    { q: "Pre-cooking fish before canning?", opts: ["Blanching", "Exhausting", "Retorting", "Sealing"], a: "Blanching" },
    { q: "Machine to seal cans?", opts: ["Double Seamer", "Vacuum packer", "Heat sealer", "Stapler"], a: "Double Seamer" },
    { q: "Defect: Can ends bulged?", opts: ["Swell", "Flipper", "Springer", "Leaker"], a: "Swell" },
    { q: "Defect: Can end flips when struck?", opts: ["Flipper", "Swell", "Hard swell", "Buckle"], a: "Flipper" },
    { q: "Standard can coating (Enamel)?", opts: ["C-enamel / R-enamel", "Paint", "Plastic", "Oil"], a: "C-enamel / R-enamel" },
    { q: "Sulfide staining (Black) is prevented by?", opts: ["C-enamel (Zinc oxide)", "R-enamel", "Acid", "Oil"], a: "C-enamel (Zinc oxide)" },
    { q: "Headspace is?", opts: ["Space between lid and food", "Vacuum", "Air outside", "Bottom space"], a: "Space between lid and food" },
    { q: "Cooling cans after retort prevents?", opts: ["Thermophilic spoilage (Stack burn)", "Rust", "Freezing", "Leaking"], a: "Thermophilic spoilage (Stack burn)" },
    { q: "Water used for cooling cans must be?", opts: ["Chlorinated", "Hot", "Salty", "Dirty"], a: "Chlorinated" },

    // --- CURING (SALTING, DRYING, SMOKING) ---
    { q: "Primary preservative in drying?", opts: ["Removal of water (Low Aw)", "Salt", "Smoke", "Heat"], a: "Removal of water (Low Aw)" },
    { q: "Sun drying depends on?", opts: ["Solar heat and wind", "Machine", "Smoke", "Electricity"], a: "Solar heat and wind" },
    { q: "Salting method: Mixing dry salt with fish?", opts: ["Dry salting / Kench", "Brining", "Pickling", "Injection"], a: "Dry salting / Kench" },
    { q: "Salting method: Soaking in salt solution?", opts: ["Brining / Wet salting", "Kench", "Dry curing", "Smoking"], a: "Brining / Wet salting" },
    { q: "Liquid extracted from fish during salting?", opts: ["Pickle / Patis", "Brine", "Water", "Oil"], a: "Pickle / Patis" },
    { q: "Saturated brine concentration?", opts: ["~26% (Salinometer 100)", "10%", "50%", "5%"], a: "~26% (Salinometer 100)" },
    { q: "Salt penetrates fish via?", opts: ["Osmosis", "Diffusion", "Active transport", "Digestion"], a: "Osmosis" },
    { q: "Impurity in salt causing bitterness?", opts: ["Magnesium / Calcium", "Sodium", "Chloride", "Iron"], a: "Magnesium / Calcium" },
    { q: "Preservative compounds in wood smoke?", opts: ["Phenols / Formaldehyde", "CO2", "Nitrogen", "Oxygen"], a: "Phenols / Formaldehyde" },
    { q: "Hot smoking cooks and smokes at?", opts: ["60°C - 80°C", "30°C", "100°C", "0°C"], a: "60°C - 80°C" },
    { q: "Cold smoking temperature?", opts: ["Below 30°C", "80°C", "100°C", "50°C"], a: "Below 30°C" },
    { q: "Carcinogen found in smoked foods?", opts: ["Benzopyrene / PAH", "Histamine", "Mercury", "Lead"], a: "Benzopyrene / PAH" },
    { q: "Fish paste fermented product?", opts: ["Bagoong", "Patis", "Burong isda", "Tinapa"], a: "Bagoong" },
    { q: "Fish sauce fermented product?", opts: ["Patis", "Bagoong", "Toyo", "Suka"], a: "Patis" },
    { q: "Fermented rice and fish?", opts: ["Burong isda / Balao-balao", "Bagoong", "Patis", "Sushi"], a: "Burong isda / Balao-balao" },
    { q: "Bacteria involved in Buro (Rice fish)?", opts: ["Lactic Acid Bacteria", "E. coli", "Salmonella", "Vibrio"], a: "Lactic Acid Bacteria" },
    { q: "Surimi is?", opts: ["Washed minced fish meat", "Dried fish", "Smoked fish", "Canned fish"], a: "Washed minced fish meat" },
    { q: "Surimi cryoprotectants?", opts: ["Sugar / Sorbitol / Polyphosphates", "Salt", "Acid", "Pepper"], a: "Sugar / Sorbitol / Polyphosphates" },
    { q: "Gel forming protein in Surimi?", opts: ["Myofibrillar (Myosin)", "Sarcoplasmic", "Stroma", "Blood"], a: "Myofibrillar (Myosin)" },
    { q: "Kamaboko is?", opts: ["Fish cake", "Fish sauce", "Fish ball", "Dried fish"], a: "Fish cake" },

    // --- QUALITY ASSURANCE & STANDARDS ---
    { q: "HACCP stands for?", opts: ["Hazard Analysis Critical Control Point", "Hazard Assessment Control Program", "Health and Care Control Point", "Hazard Analysis Critical Check"], a: "Hazard Analysis Critical Control Point" },
    { q: "First principle of HACCP?", opts: ["Hazard Analysis", "Determine CCP", "Monitor", "Verify"], a: "Hazard Analysis" },
    { q: "A step where hazard can be controlled?", opts: ["CCP (Critical Control Point)", "CP (Control Point)", "Hazard Analysis", "Monitoring"], a: "CCP (Critical Control Point)" },
    { q: "GMP stands for?", opts: ["Good Manufacturing Practices", "General Manufacturing Process", "Good Maintenance Program", "Global Marine Policy"], a: "Good Manufacturing Practices" },
    { q: "SSOP stands for?", opts: ["Sanitation Standard Operating Procedures", "Standard Safety Operating Procedure", "Safe Sanitation Order Program", "Standard System of Operation"], a: "Sanitation Standard Operating Procedures" },
    { q: "Codex Alimentarius is?", opts: ["International Food Standards", "Local Law", "Company Rule", "Recipe Book"], a: "International Food Standards" },
    { q: "Sensory evaluation uses?", opts: ["Senses (Sight, Smell, Taste, Touch)", "Machines", "Chemicals", "Computers"], a: "Senses (Sight, Smell, Taste, Touch)" },
    { q: "Objective assessment of freshness?", opts: ["TMA Test / K-value", "Smelling", "Looking", "Touching"], a: "TMA Test / K-value" },
    { q: "K-value measures?", opts: ["ATP degradation", "Fat content", "Protein content", "Salt"], a: "ATP degradation" },
    { q: "TMA-N limit for rejection?", opts: ["10-15 mg%", "1 mg%", "100 mg%", "0 mg%"], a: "10-15 mg%" },
    { q: "Fat content analysis method?", opts: ["Soxhlet", "Kjeldahl", "Ashing", "Titration"], a: "Soxhlet" },
    { q: "Protein content analysis method?", opts: ["Kjeldahl", "Soxhlet", "Oven drying", "pH"], a: "Kjeldahl" },
    { q: "Moisture content analysis?", opts: ["Oven drying method", "Soxhlet", "Kjeldahl", "Titration"], a: "Oven drying method" },
    { q: "Ash content analysis?", opts: ["Muffle furnace", "Oven", "Freezer", "Blender"], a: "Muffle furnace" },
    { q: "Iodine value measures?", opts: ["Degree of unsaturation (Fats)", "Protein", "Salt", "Water"], a: "Degree of unsaturation (Fats)" },
    { q: "Peroxide value measures?", opts: ["Primary oxidation (Rancidity)", "Protein", "Bacteria", "Vitamins"], a: "Primary oxidation (Rancidity)" },
    { q: "TBA test measures?", opts: ["Secondary oxidation (Aldehydes)", "Primary oxidation", "Protein", "Salt"], a: "Secondary oxidation (Aldehydes)" },
    { q: "Vacuum packaging removes?", opts: ["Oxygen", "Water", "Light", "Bacteria"], a: "Oxygen" },
    { q: "Modified Atmosphere Packaging (MAP) uses?", opts: ["CO2 / N2 gas mix", "Oxygen only", "Vacuum", "Air"], a: "CO2 / N2 gas mix" },
    { q: "Active packaging includes?", opts: ["Oxygen absorbers", "Vacuum", "Canning", "Freezing"], a: "Oxygen absorbers" },
  // --- BATCH 2: QUESTIONS 101-200 ---
    // --- FOOD CHEMISTRY & BIOCHEMISTRY ---
    { q: "Reaction causing browning in dried fish (Non-enzymatic)?", opts: ["Maillard Reaction", "Enzymatic Browning", "Caramelization", "Lipid Oxidation"], a: "Maillard Reaction" },
    { q: "Maillard reaction occurs between?", opts: ["Amino acids and Reducing sugars", "Fat and Oxygen", "Protein and Salt", "Acid and Base"], a: "Amino acids and Reducing sugars" },
    { q: "Protein denaturation is caused by?", opts: ["Heat / Acid / Salt", "Freezing only", "Cold", "Darkness"], a: "Heat / Acid / Salt" },
    { q: "Effect of denaturation on texture?", opts: ["Toughening / Loss of water holding capacity", "Softening", "Gelation", "Liquefaction"], a: "Toughening / Loss of water holding capacity" },
    { q: "Omega-3 fatty acids are famous for?", opts: ["Cardiovascular health", "Bone strength", "Vision", "Digestion"], a: "Cardiovascular health" },
    { q: "Major Omega-3 found in fish?", opts: ["EPA and DHA", "Linoleic Acid", "Oleic Acid", "Stearic Acid"], a: "EPA and DHA" },
    { q: "Rancidity producing 'paint-like' smell?", opts: ["Oxidative Rancidity", "Hydrolytic Rancidity", "Putrefaction", "Fermentation"], a: "Oxidative Rancidity" },
    { q: "Hydrolytic rancidity is caused by?", opts: ["Lipase enzyme splitting fats", "Oxygen", "Bacteria", "Heat"], a: "Lipase enzyme splitting fats" },
    { q: "Yellowing of salt fish (Rusting) is due to?", opts: ["Oxidation of fat", "Bacteria", "Mold", "Too much salt"], a: "Oxidation of fat" },
    { q: "Antioxidant used to prevent rancidity?", opts: ["BHT / BHA / Tocopherol (Vit E)", "Salt", "Sugar", "Vinegar"], a: "BHT / BHA / Tocopherol (Vit E)" },
    { q: "Specific spoilage organism (SSO) in iced fish?", opts: ["Pseudomonas / Shewanella", "E. coli", "Salmonella", "Staphylococcus"], a: "Pseudomonas / Shewanella" },
    { q: "Black spot in shrimp (Melanosis) is caused by?", opts: ["Polyphenoloxidase enzymes", "Bacteria", "Virus", "Dirt"], a: "Polyphenoloxidase enzymes" },
    { q: "Chemical to prevent Melanosis in shrimp?", opts: ["Sodium Metabisulfite", "Formalin", "Salt", "Sugar"], a: "Sodium Metabisulfite" },
    { q: "Gaping in fillets is caused by?", opts: ["Breakdown of connective tissue (Collagen)", "Bacteria", "Freezing", "Knife"], a: "Breakdown of connective tissue (Collagen)" },
    { q: "Connective tissue in fish is called?", opts: ["Myocommata", "Myotomes", "Skin", "Bone"], a: "Myocommata" },
    { q: "Muscle blocks in fish are called?", opts: ["Myotomes", "Myocommata", "Fillet", "Steak"], a: "Myotomes" },

    // --- PROCESSING EQUIPMENT & PACKAGING ---
    { q: "Can seam defect: 'Droop'?", opts: ["Smooth projection of double seam", "Sharp edge", "Cut seam", "Open seam"], a: "Smooth projection of double seam" },
    { q: "Can seam defect: 'Vee'?", opts: ["Sharp projection at overlap", "Smooth", "Round", "Flat"], a: "Sharp projection at overlap" },
    { q: "Can seam part: Body Hook?", opts: ["Flange of can body bent down", "Lid bent up", "Rubber seal", "Bottom"], a: "Flange of can body bent down" },
    { q: "Can seam part: Cover Hook?", opts: ["Curl of lid bent up", "Body bent down", "Side", "Label"], a: "Curl of lid bent up" },
    { q: "Overlap length in a seam is critical for?", opts: ["Sealing / Hermeticity", "Appearance", "Labeling", "Stacking"], a: "Sealing / Hermeticity" },
    { q: "Retort pouch is made of?", opts: ["Polyester / Aluminum Foil / Polypropylene", "Paper", "Glass", "Pure Plastic"], a: "Polyester / Aluminum Foil / Polypropylene" },
    { q: "Function of Aluminum foil in pouches?", opts: ["Barrier to light and oxygen", "Strength", "Heat seal", "Cost"], a: "Barrier to light and oxygen" },
    { q: "Function of Polypropylene (PP) in pouches?", opts: ["Heat sealing layer (inner)", "Outer strength", "Barrier", "Color"], a: "Heat sealing layer (inner)" },
    { q: "Glass jars are processed using?", opts: ["Water bath with overpressure", "Steam only", "Oven", "Microwave"], a: "Water bath with overpressure" },
    { q: "Why use overpressure for glass jars?", opts: ["Prevent lids from popping off", "Cook faster", "Kill bacteria", "Clean jars"], a: "Prevent lids from popping off" },
    { q: "Smokehouse type: Torry Kiln?", opts: ["Mechanical / Controlled draft", "Traditional", "Open fire", "Solar"], a: "Mechanical / Controlled draft" },
    { q: "Drier type: Cabinet dryer?", opts: ["Trays in a closed chamber", "Sun drying", "Drum", "Spray"], a: "Trays in a closed chamber" },
    { q: "Drier type: Spray dryer is for?", opts: ["Powdered products (Fish hydrolysate)", "Whole fish", "Fillets", "Squid"], a: "Powdered products (Fish hydrolysate)" },
    { q: "Machine removing scales?", opts: ["Scaler", "Skinner", "Header", "Filleting machine"], a: "Scaler" },
    { q: "Machine removing skin?", opts: ["Skinner", "Scaler", "Bone separator", "Retort"], a: "Skinner" },
    { q: "Deboning machine works by?", opts: ["Pressing meat through holes (leaving bone)", "Cutting", "Vacuum", "Chemicals"], a: "Pressing meat through holes (leaving bone)" },

    // --- NON-TRADITIONAL & BY-PRODUCTS ---
    { q: "Fish Meal is primarily used for?", opts: ["Animal / Aquafeed", "Human food", "Fertilizer", "Fuel"], a: "Animal / Aquafeed" },
    { q: "Fish Silage is made by?", opts: ["Adding acid to liquefy fish", "Drying", "Cooking", "Freezing"], a: "Adding acid to liquefy fish" },
    { q: "Acid used in fish silage?", opts: ["Formic / Sulfuric acid", "Acetic acid", "Citric acid", "Water"], a: "Formic / Sulfuric acid" },
    { q: "Fish Protein Concentrate (FPC) type A is?", opts: ["Odorless and Tasteless powder", "Fishy paste", "Liquid", "Oil"], a: "Odorless and Tasteless powder" },
    { q: "Isinglass is made from?", opts: ["Swim bladder", "Skin", "Bones", "Scales"], a: "Swim bladder" },
    { q: "Isinglass is used for?", opts: ["Clarifying wine/beer", "Glue", "Food", "Leather"], a: "Clarifying wine/beer" },
    { q: "Shark liver oil is rich in?", opts: ["Squalene / Vitamin A", "Protein", "Calcium", "Iron"], a: "Squalene / Vitamin A" },
    { q: "Chitin is extracted from?", opts: ["Shrimp/Crab shells", "Fish skin", "Seaweed", "Bones"], a: "Shrimp/Crab shells" },
    { q: "Chitosan is derived from?", opts: ["Deacetylation of Chitin", "Fish oil", "Algae", "Salt"], a: "Deacetylation of Chitin" },
    { q: "Uses of Chitosan?", opts: ["Antimicrobial / Flocculant / Medical", "Fuel", "Fertilizer", "Paint"], a: "Antimicrobial / Flocculant / Medical" },
    { q: "Fish leather is made from?", opts: ["Skin (Tilapia/Shark)", "Guts", "Bones", "Scales"], a: "Skin (Tilapia/Shark)" },
    { q: "Pearl essence (Guanine) comes from?", opts: ["Fish scales", "Eyes", "Liver", "Blood"], a: "Fish scales" },

    // --- SEAWEED PROCESSING ---
    { q: "Carrageenan is extracted from?", opts: ["Red algae (Kappaphycus/Eucheuma)", "Brown algae", "Green algae", "Seagrass"], a: "Red algae (Kappaphycus/Eucheuma)" },
    { q: "Types of Carrageenan?", opts: ["Kappa, Iota, Lambda", "Alpha, Beta, Gamma", "A, B, C", "X, Y, Z"], a: "Kappa, Iota, Lambda" },
    { q: "Kappa carrageenan gel is?", opts: ["Firm and brittle", "Soft and elastic", "Non-gelling", "Liquid"], a: "Firm and brittle" },
    { q: "Iota carrageenan gel is?", opts: ["Soft and elastic", "Firm", "Brittle", "Hard"], a: "Soft and elastic" },
    { q: "Agar is extracted from?", opts: ["Gracilaria / Gelidium", "Kappaphycus", "Sargassum", "Ulva"], a: "Gracilaria / Gelidium" },
    { q: "Difference between Agar and Carrageenan?", opts: ["Agar has higher melting point / Non-ionic", "Carrageenan is stronger", "Same", "Color"], a: "Agar has higher melting point / Non-ionic" },
    { q: "Alginate is extracted from?", opts: ["Brown algae (Sargassum/Kelp)", "Red algae", "Green algae", "Coral"], a: "Brown algae (Sargassum/Kelp)" },
    { q: "Alginate is used as?", opts: ["Thickener / Stabilizer / Dental impression", "Fertilizer", "Fuel", "Dye"], a: "Thickener / Stabilizer / Dental impression" },
    { q: "Method of extracting Agar?", opts: ["Boiling in water -> Freezing-Thawing", "Alcohol precipitation", "Acid hydrolysis", "Drying"], a: "Boiling in water -> Freezing-Thawing" },
    { q: "Refined Carrageenan (RC) vs Semi-Refined (SRC)?", opts: ["RC is pure extract, SRC contains cellulose", "SRC is purer", "RC is liquid", "SRC is gas"], a: "RC is pure extract, SRC contains cellulose" },

    // --- HYGIENE & SANITATION ---
    { q: "Chlorine concentration for hand dip?", opts: ["50 ppm", "200 ppm", "500 ppm", "10 ppm"], a: "50 ppm" },
    { q: "Chlorine concentration for processing water?", opts: ["5-10 ppm", "100 ppm", "0 ppm", "500 ppm"], a: "5-10 ppm" },
    { q: "Chlorine concentration for equipment sanitation?", opts: ["100-200 ppm", "10 ppm", "1 ppm", "1000 ppm"], a: "100-200 ppm" },
    { q: "Contact time for chlorine to work?", opts: ["At least 1-2 minutes", "1 second", "1 hour", "Instant"], a: "At least 1-2 minutes" },
    { q: "Sanitizer effective against Listeria?", opts: ["Quaternary Ammonium Compounds (QUATS)", "Water", "Soap", "Salt"], a: "Quaternary Ammonium Compounds (QUATS)" },
    { q: "Biofilm is?", opts: ["Layer of bacteria protecting themselves", "Plastic film", "Packaging", "Soap scum"], a: "Layer of bacteria protecting themselves" },
    { q: "Hardest bacteria to remove?", opts: ["Biofilm formers", "Planktonic bacteria", "Good bacteria", "Yeast"], a: "Biofilm formers" },
    { q: "Cleaning vs Sanitizing?", opts: ["Cleaning removes dirt; Sanitizing kills bacteria", "Same thing", "Sanitizing removes dirt", "Cleaning kills bacteria"], a: "Cleaning removes dirt; Sanitizing kills bacteria" },
    { q: "Detergent function?", opts: ["Remove soil/grease", "Kill bacteria", "Dry surface", "Polish"], a: "Remove soil/grease" },
    { q: "Cross-contamination is?", opts: ["Transfer of bacteria from dirty to clean area", "Cleaning", "Cooking", "Packaging"], a: "Transfer of bacteria from dirty to clean area" },
    { q: "Personal hygiene rule?", opts: ["No jewelry / Hairnet required", "Wear makeup", "Long nails", "Smoking allowed"], a: "No jewelry / Hairnet required" },
    { q: "Hand washing duration?", opts: ["20 seconds", "5 seconds", "1 minute", "No need"], a: "20 seconds" },

    // --- FOOD LAWS & CERTIFICATIONS ---
    { q: "Halal certification is for?", opts: ["Muslim dietary laws", "Jewish laws", "Vegetarians", "Organic"], a: "Muslim dietary laws" },
    { q: "Kosher certification is for?", opts: ["Jewish dietary laws", "Muslim laws", "Hindus", "Vegans"], a: "Jewish dietary laws" },
    { q: "Requirement for Kosher fish?", opts: ["Must have fins and scales", "Shellfish allowed", "Any fish", "No blood"], a: "Must have fins and scales" },
    { q: "Is Shellfish Halal?", opts: ["Generally Yes (Sunni), depends on sect", "No", "Only crab", "Only shrimp"], a: "Generally Yes (Sunni), depends on sect" },
    { q: "Organic Aquaculture bans?", opts: ["GMOs / Synthetic antibiotics", "Natural feed", "Probiotics", "Water"], a: "GMOs / Synthetic antibiotics" },
    { q: "Traceability means?", opts: ["Ability to track food from farm to fork", "Tracking truck speed", "Tracing paper", "GPS"], a: "Ability to track food from farm to fork" },
    { q: "ISO 22000 covers?", opts: ["Food Safety Management Systems", "Quality only", "Environment", "Worker safety"], a: "Food Safety Management Systems" },
    { q: "ISO 9001 covers?", opts: ["Quality Management Systems", "Food Safety", "Environment", "Automotive"], a: "Quality Management Systems" },
    { q: "ISO 14001 covers?", opts: ["Environmental Management", "Food Safety", "Quality", "Energy"], a: "Environmental Management" }
];
